import type { Practice } from '../types/toolkit';

export const SAMPLE_PRACTICES: Practice[] = [
  {
    id: 'prac_001_box_breathing',
    title: 'Box Breathing',
    subtitle: '4-4-4-4 nervous system reset',
    pillar_id: 'ER',
    duration_minutes: 3,
    difficulty: 'beginner',
    modality: 'breathing',
    intro: 'Box breathing (also called square breathing) calms your nervous system by creating a rhythmic pattern that signals safety to your body. Used by Navy SEALs, athletes, and anyone needing quick regulation.',
    steps: [
      {
        step_number: 1,
        instruction: 'Breathe in through your nose for 4 seconds',
        duration_seconds: 4,
        voice_guidance: 'Breathe in... two, three, four',
      },
      {
        step_number: 2,
        instruction: 'Hold your breath for 4 seconds',
        duration_seconds: 4,
        voice_guidance: 'Hold... two, three, four',
      },
      {
        step_number: 3,
        instruction: 'Breathe out through your mouth for 4 seconds',
        duration_seconds: 4,
        voice_guidance: 'Breathe out... two, three, four',
      },
      {
        step_number: 4,
        instruction: 'Hold empty for 4 seconds',
        duration_seconds: 4,
        voice_guidance: 'Hold... two, three, four',
      },
      {
        step_number: 5,
        instruction: 'Repeat for 5 rounds total (repeat steps 1-4)',
        duration_seconds: 64,
        voice_guidance: 'Continue this rhythm for 4 more rounds',
      },
    ],
    schema_targets: ['window_of_tolerance', 'nervous_system_regulation', 'embodiment'],
    state_band_allowed: ['green', 'amber', 'red'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'How does your body feel now?',
        'What shifted?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_001_er_window', 'art_002_er_triggers'],
    related_insights: ['ins_003_regulation', 'ins_010_nervous'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_002_grounding',
    title: '5-4-3-2-1 Grounding',
    subtitle: 'Anchor yourself in the present moment',
    pillar_id: 'ER',
    duration_minutes: 5,
    difficulty: 'beginner',
    modality: 'sensory',
    intro: "When your mind is racing or you're dissociating, this sensory grounding practice brings you back to the present by engaging all five senses.",
    steps: [
      {
        step_number: 1,
        instruction: 'Name 5 things you can SEE around you',
        voice_guidance: 'Look around. Name 5 things you can see. Say them out loud if possible.',
      },
      {
        step_number: 2,
        instruction: 'Name 4 things you can TOUCH or FEEL',
        voice_guidance: 'Now notice 4 things you can physically feel. Your feet on the floor. The chair beneath you. The air on your skin.',
      },
      {
        step_number: 3,
        instruction: 'Name 3 things you can HEAR',
        voice_guidance: 'Listen. What are 3 sounds you can hear right now? Distant or close.',
      },
      {
        step_number: 4,
        instruction: 'Name 2 things you can SMELL',
        voice_guidance: 'What can you smell? If nothing, name 2 smells you like.',
      },
      {
        step_number: 5,
        instruction: 'Name 1 thing you can TASTE',
        voice_guidance: 'What can you taste? Or name a taste you enjoy.',
      },
      {
        step_number: 6,
        instruction: 'Take 3 deep breaths',
        duration_seconds: 15,
        voice_guidance: 'Now breathe. Three slow, deep breaths. In... and out.',
      },
    ],
    schema_targets: ['grounding', 'present_moment', 'nervous_system_regulation'],
    state_band_allowed: ['amber', 'red', 'shutdown'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'Do you feel more present?',
        'What changed?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_001_er_window', 'art_002_er_triggers'],
    related_insights: ['ins_005_triggers', 'ins_010_nervous'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_003_pause',
    title: 'The 90-Second Pause',
    subtitle: 'Create space between stimulus and response',
    pillar_id: 'DM',
    duration_minutes: 2,
    difficulty: 'beginner',
    modality: 'reflection',
    intro: 'Research shows that an emotion, if not resisted, lasts about 90 seconds. This practice creates space for the wave to pass before you act.',
    steps: [
      {
        step_number: 1,
        instruction: "Notice you're activated (triggered, angry, craving)",
        voice_guidance: 'First, notice. You\'re activated. Something triggered you. Name it: "I\'m feeling triggered."',
      },
      {
        step_number: 2,
        instruction: 'Commit to 90 seconds before acting',
        voice_guidance: 'Make a deal with yourself: 90 seconds. You can do anything after, but give yourself 90 seconds first.',
      },
      {
        step_number: 3,
        instruction: 'Focus on your breath for 90 seconds',
        duration_seconds: 90,
        voice_guidance: 'Breathe. In and out. Don\'t try to change the feeling. Just breathe through it. 90 seconds.',
      },
      {
        step_number: 4,
        instruction: 'Check in: What do you need now?',
        voice_guidance: 'Now check in. The peak has passed. What do you actually need? Call someone? Move your body? Rest?',
      },
    ],
    schema_targets: ['choice_access', 'impulse_control', 'pause'],
    state_band_allowed: ['amber', 'red'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'Did the intensity shift?',
        'What became clear?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_010_dm_decisions'],
    related_insights: ['ins_008_reactions', 'ins_019_pause', 'ins_020_choice'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_004_values',
    title: 'Values Clarification',
    subtitle: 'Discover what actually matters to you',
    pillar_id: 'II',
    duration_minutes: 10,
    difficulty: 'intermediate',
    modality: 'reflection',
    intro: 'When you\'re not sure who you are beyond recovery, this practice helps you reconnect with your core values—the compass that guides your choices.',
    steps: [
      {
        step_number: 1,
        instruction: 'Read this list of values and notice which ones resonate: Growth, Connection, Creativity, Health, Freedom, Integrity, Courage, Compassion, Justice, Joy, Peace, Adventure, Learning, Service',
        voice_guidance: 'Take your time. Which values light something up in you? Don\'t think about what you should value. Notice what you do value.',
      },
      {
        step_number: 2,
        instruction: 'Choose your top 5 values',
        voice_guidance: 'Narrow it down. Your top 5. The ones that feel most true to who you want to be.',
      },
      {
        step_number: 3,
        instruction: 'For each value, write: What would living this value look like today?',
        voice_guidance: 'Get specific. If you value connection, what would that look like today? A text? A phone call? Showing up honestly?',
      },
      {
        step_number: 4,
        instruction: 'Choose ONE small action aligned with ONE value to do this week',
        voice_guidance: 'Just one. Don\'t overwhelm yourself. One small action that moves you toward who you want to become.',
      },
    ],
    schema_targets: ['values_clarity', 'identity', 'meaning_making'],
    state_band_allowed: ['green', 'amber'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'What value will you practice this week?',
        'What action will you take?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_005_sc_identity', 'art_009_ii_meaning'],
    related_insights: ['ins_006_identity', 'ins_009_purpose', 'ins_014_becoming'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_005_boundary',
    title: 'Boundary Practice',
    subtitle: 'Say no without guilt',
    pillar_id: 'CR',
    duration_minutes: 5,
    difficulty: 'intermediate',
    modality: 'reflection',
    intro: 'Boundaries protect your recovery. This practice helps you identify, communicate, and hold boundaries without shame.',
    steps: [
      {
        step_number: 1,
        instruction: 'Identify one area where you need a boundary (time, energy, behavior, relationship)',
        voice_guidance: 'Think about where you\'re overextended. Where are you saying yes when you mean no?',
      },
      {
        step_number: 2,
        instruction: 'Get clear on your limit: What is the boundary?',
        voice_guidance: 'Be specific. "I won\'t take calls after 9pm." "I won\'t lend money." "I won\'t attend events where people are drinking." Get clear.',
      },
      {
        step_number: 3,
        instruction: 'Script how you\'ll communicate it: "I can\'t ___." or "That doesn\'t work for me."',
        voice_guidance: 'Practice saying it out loud. No justification. No apology. Just clear communication.',
      },
      {
        step_number: 4,
        instruction: 'Anticipate the guilt and plan your response',
        voice_guidance: 'Guilt will show up. That\'s normal when you\'re changing a pattern. Remind yourself: boundaries protect my recovery.',
      },
      {
        step_number: 5,
        instruction: 'Commit to holding this boundary once this week',
        voice_guidance: 'One boundary. One time. Notice what happens.',
      },
    ],
    schema_targets: ['boundaries', 'self_advocacy', 'worthiness'],
    state_band_allowed: ['green', 'amber'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'What boundary will you set?',
        'How will you communicate it?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_008_cr_boundaries'],
    related_insights: ['ins_007_boundaries', 'ins_011_no'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_006_reach_out',
    title: 'Reach Out Practice',
    subtitle: 'Break isolation with one text',
    pillar_id: 'CR',
    duration_minutes: 3,
    difficulty: 'beginner',
    modality: 'reflection',
    intro: 'Isolation feeds addiction. Connection supports recovery. This practice makes reaching out concrete and doable.',
    steps: [
      {
        step_number: 1,
        instruction: 'Think of one safe person (sponsor, therapist, friend in recovery, supportive family member)',
        voice_guidance: 'Who\'s one person who has shown up for you? Who feels safe?',
      },
      {
        step_number: 2,
        instruction: 'Decide what you want to share (struggle, win, truth, need)',
        voice_guidance: 'You don\'t have to share everything. Just something real. "I\'m struggling today." "I had a win." "I need support."',
      },
      {
        step_number: 3,
        instruction: 'Send one text right now. Don\'t wait.',
        voice_guidance: 'Don\'t overthink it. Just send it. "Hey, feeling rough today. Can we talk?" That\'s enough.',
      },
      {
        step_number: 4,
        instruction: 'Notice what you feel after sending it',
        voice_guidance: 'Relief? Fear? Vulnerability? Just notice. You took action against isolation. That matters.',
      },
    ],
    schema_targets: ['connection', 'vulnerability', 'support_seeking'],
    state_band_allowed: ['amber', 'red', 'shutdown'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'Who did you reach out to?',
        'What did you share?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_007_cr_connection'],
    related_insights: ['ins_002_isolation', 'ins_013_belonging'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_007_self_compassion',
    title: 'Self-Compassion Break',
    subtitle: 'Speak to yourself like someone you love',
    pillar_id: 'SR',
    duration_minutes: 5,
    difficulty: 'beginner',
    modality: 'reflection',
    intro: 'Based on Kristin Neff\'s self-compassion research, this practice helps you respond to yourself with kindness instead of shame.',
    steps: [
      {
        step_number: 1,
        instruction: 'Name what you\'re struggling with: "I\'m struggling with ___"',
        voice_guidance: 'Be honest. What\'s hard right now? Say it out loud.',
      },
      {
        step_number: 2,
        instruction: 'Acknowledge this is hard: "This is a moment of suffering" or "This is difficult"',
        voice_guidance: 'Don\'t minimize it. Name the difficulty. This is hard.',
      },
      {
        step_number: 3,
        instruction: 'Remind yourself of common humanity: "I\'m not alone. Others feel this too."',
        voice_guidance: 'You\'re not the only one struggling. This is part of being human.',
      },
      {
        step_number: 4,
        instruction: 'Offer yourself kindness: "May I be kind to myself" or "May I give myself what I need"',
        voice_guidance: 'Place your hand on your heart if that helps. Speak to yourself like you\'d speak to someone you love.',
      },
      {
        step_number: 5,
        instruction: 'Ask: "What do I need right now?"',
        voice_guidance: 'What would actually help? Rest? Connection? Movement? A boundary? Listen.',
      },
    ],
    schema_targets: ['self_compassion', 'shame_spiral', 'worthiness'],
    state_band_allowed: ['amber', 'red'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'What shifted?',
        'What do you need?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_003_sr_shame', 'art_006_sc_worth'],
    related_insights: ['ins_001_shame', 'ins_012_worth', 'ins_016_enough'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_008_mirror',
    title: 'Mirror Work',
    subtitle: 'Look yourself in the eye',
    pillar_id: 'SC',
    duration_minutes: 3,
    difficulty: 'advanced',
    modality: 'reflection',
    intro: 'This practice, popularized by Louise Hay, can feel uncomfortable. That\'s normal. It builds the capacity to see yourself with compassion.',
    steps: [
      {
        step_number: 1,
        instruction: 'Stand in front of a mirror and make eye contact with yourself',
        voice_guidance: 'This might feel awkward. That\'s okay. Just look.',
      },
      {
        step_number: 2,
        instruction: 'Say your name out loud: "[Your name], I see you"',
        voice_guidance: 'Say it like you mean it. "[Name], I see you."',
      },
      {
        step_number: 3,
        instruction: 'Say: "You\'re doing the best you can"',
        voice_guidance: 'Even if you don\'t believe it yet, say it. "You\'re doing the best you can."',
      },
      {
        step_number: 4,
        instruction: 'Say: "You are worthy of love"',
        voice_guidance: 'Say it. "You are worthy of love." Notice what comes up.',
      },
      {
        step_number: 5,
        instruction: 'Stay with whatever emotion arises. Don\'t push it away.',
        voice_guidance: 'If tears come, let them. If resistance shows up, notice it. This is hard work.',
      },
    ],
    schema_targets: ['worthiness', 'self_compassion', 'shame_spiral'],
    state_band_allowed: ['green', 'amber'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'What came up for you?',
        'What was hardest?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_006_sc_worth'],
    related_insights: ['ins_012_worth', 'ins_016_enough'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_009_voicing',
    title: 'Voice Your Truth',
    subtitle: 'Speak what you\'ve been hiding',
    pillar_id: 'SR',
    duration_minutes: 5,
    difficulty: 'intermediate',
    modality: 'reflection',
    intro: 'Secrets keep you sick. This practice helps you identify what you\'re hiding and take one step toward speaking it.',
    steps: [
      {
        step_number: 1,
        instruction: 'Identify one thing you\'ve been hiding (feeling, struggle, need, truth)',
        voice_guidance: 'What are you carrying alone? What feels heavy? What would you say if you weren\'t afraid?',
      },
      {
        step_number: 2,
        instruction: 'Write it down exactly as it is, no editing',
        voice_guidance: 'Don\'t make it prettier. Don\'t soften it. Write the raw truth.',
      },
      {
        step_number: 3,
        instruction: 'Read it out loud to yourself',
        voice_guidance: 'Hear yourself say it. Notice what that feels like.',
      },
      {
        step_number: 4,
        instruction: 'Decide: Who is ONE safe person you could share this with?',
        voice_guidance: 'Not everyone. One person. Who could handle this truth?',
      },
      {
        step_number: 5,
        instruction: 'Commit to sharing it with them this week',
        voice_guidance: 'Make a plan. When? How? In person, text, call? Commit.',
      },
    ],
    schema_targets: ['authenticity', 'secrecy', 'shame_spiral'],
    state_band_allowed: ['green', 'amber'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'What are you ready to speak?',
        'Who will you tell?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_004_sr_secrecy'],
    related_insights: ['ins_004_secrecy', 'ins_015_truth'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'prac_010_writing',
    title: 'Unsent Letter',
    subtitle: 'Write what you can\'t say yet',
    pillar_id: 'II',
    duration_minutes: 15,
    difficulty: 'intermediate',
    modality: 'reflection',
    intro: 'Sometimes you need to process before you can speak. This practice gives you a container to explore what you\'re feeling without the pressure of sharing.',
    steps: [
      {
        step_number: 1,
        instruction: 'Choose who you\'re writing to (yourself, someone else, your addiction, your younger self)',
        voice_guidance: 'Who needs to hear from you? Or who do you need to speak to?',
      },
      {
        step_number: 2,
        instruction: 'Set a timer for 10 minutes and write without stopping',
        duration_seconds: 600,
        voice_guidance: 'Don\'t edit. Don\'t censor. Just write. Whatever comes. Keep your hand moving.',
      },
      {
        step_number: 3,
        instruction: 'Read what you wrote',
        voice_guidance: 'Read it to yourself. Notice what surprises you.',
      },
      {
        step_number: 4,
        instruction: 'Decide: Is this for you only, or will you share it?',
        voice_guidance: 'You don\'t have to send it. This can be just for you. Or maybe it becomes something you share. You decide.',
      },
    ],
    schema_targets: ['meaning_making', 'emotional_processing', 'identity'],
    state_band_allowed: ['green', 'amber'],
    response_contract: {
      completion_check: true,
      exit_questions: [
        'What came up for you?',
        'What did you discover?',
      ],
      proof_capture_mode: 'practice_completion',
    },
    related_articles: ['art_005_sc_identity', 'art_009_ii_meaning'],
    related_insights: ['ins_006_identity', 'ins_009_purpose', 'ins_017_becoming'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
];