import type { Meeting } from '../types/navigate';

export const SAMPLE_MEETINGS: Meeting[] = [
  {
    id: 'meet_001',
    name: 'Downtown AA',
    type: '12_step',
    format: 'in_person',
    address: '123 Main St, San Francisco, CA 94102',
    lat: 37.7749,
    lng: -122.4194,
    schedule: {
      day: 'monday',
      time: '19:00',
      frequency: 'weekly',
    },
    description: 'Open AA meeting. All are welcome. Focus on steps 1-3.',
    accessibility: ['wheelchair_accessible', 'public_transit'],
    created_at: '2024-12-30T00:00:00Z',
  },
  {
    id: 'meet_002',
    name: 'SMART Recovery Online',
    type: 'SMART',
    format: 'virtual',
    virtual_link: 'https://zoom.us/j/example123',
    schedule: {
      day: 'tuesday',
      time: '18:30',
      frequency: 'weekly',
    },
    description: 'Science-based recovery support. Online via Zoom.',
    accessibility: ['virtual'],
    created_at: '2024-12-30T00:00:00Z',
  },
  {
    id: 'meet_003',
    name: 'Refuge Recovery',
    type: 'Refuge',
    format: 'in_person',
    address: '456 Oak Ave, San Francisco, CA 94103',
    lat: 37.7699,
    lng: -122.4072,
    schedule: {
      day: 'wednesday',
      time: '19:30',
      frequency: 'weekly',
    },
    description: 'Buddhist-inspired recovery meeting. Meditation and discussion.',
    accessibility: ['wheelchair_accessible'],
    created_at: '2024-12-30T00:00:00Z',
  },
  {
    id: 'meet_004',
    name: 'Early Morning AA',
    type: '12_step',
    format: 'hybrid',
    address: '789 Market St, San Francisco, CA 94104',
    virtual_link: 'https://zoom.us/j/example456',
    lat: 37.7879,
    lng: -122.4074,
    schedule: {
      day: 'monday',
      time: '07:00',
      frequency: 'weekly',
    },
    description: 'Start your week right. In-person or virtual. Big Book study.',
    accessibility: ['wheelchair_accessible', 'virtual', 'public_transit'],
    created_at: '2024-12-30T00:00:00Z',
  },
  {
    id: 'meet_005',
    name: "Women's AA",
    type: '12_step',
    format: 'in_person',
    address: '321 Valencia St, San Francisco, CA 94110',
    lat: 37.7599,
    lng: -122.4214,
    schedule: {
      day: 'thursday',
      time: '18:00',
      frequency: 'weekly',
    },
    description: 'Women-only meeting. Safe space for sharing.',
    accessibility: ['women_only'],
    created_at: '2024-12-30T00:00:00Z',
  },
];