import { jsxs as _jsxs, jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
export const Console = ({ events, personName = 'Patient' }) => {
    const heatTrend = events.slice(-5).reduce((acc, e) => {
        const bands = { safe: 1, caution: 2, alert: 3 };
        return [...acc, bands[e.contract.heatBand]];
    }, []);
    const avgHeat = heatTrend.length > 0 ? (heatTrend.reduce((a, b) => a + b) / heatTrend.length).toFixed(1) : '—';
    const successRate = events.length > 0
        ? (((events.filter((e) => e.status === 'captured').length / events.length) * 100).toFixed(0) + '%')
        : '—';
    return (_jsx("div", { className: "card", role: "region", "aria-label": "Clinician console", children: _jsxs("div", { className: "stack", style: { gap: 12 }, children: [_jsxs("div", { className: "row", style: { justifyContent: 'space-between' }, children: [_jsxs("h2", { className: "title", style: { margin: 0 }, children: ["Console \u00B7 ", personName] }), _jsx("span", { className: "label", children: "Live signal" })] }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10 }, children: [_jsxs("div", { className: "panel", style: { padding: '10px 12px' }, children: [_jsx("p", { className: "label", style: { margin: 0 }, children: "Events" }), _jsx("p", { className: "title", style: { margin: '4px 0 0 0', fontSize: 24 }, children: events.length })] }), _jsxs("div", { className: "panel", style: { padding: '10px 12px' }, children: [_jsx("p", { className: "label", style: { margin: 0 }, children: "Success rate" }), _jsx("p", { className: "title", style: { margin: '4px 0 0 0', fontSize: 24 }, children: successRate })] }), _jsxs("div", { className: "panel", style: { padding: '10px 12px' }, children: [_jsx("p", { className: "label", style: { margin: 0 }, children: "Avg heat" }), _jsx("p", { className: "title", style: { margin: '4px 0 0 0', fontSize: 24 }, children: avgHeat })] })] }), _jsx("hr", { className: "divider" }), _jsxs("div", { className: "stack", style: { gap: 8 }, children: [_jsx("p", { className: "label", children: "Event signal stream" }), _jsx("div", { style: { maxHeight: 240, overflowY: 'auto' }, className: "list", children: events.length === 0 ? (_jsx("p", { className: "subtitle", style: { margin: 0 }, children: "No events yet. Awaiting first proof capture." })) : (events
                                .slice()
                                .reverse()
                                .map((e) => (_jsxs("div", { className: "list-row", style: { paddingTop: 8, paddingBottom: 8 }, role: "listitem", children: [_jsx("div", { className: `badge ${e.contract.heatBand}`, children: e.status }), _jsxs("div", { className: "stack", style: { gap: 2 }, children: [_jsx("span", { style: { fontWeight: 600, fontSize: 13 }, children: e.contract.primitive }), _jsxs("span", { className: "subtitle", style: { margin: 0, fontSize: 11 }, children: [e.contract.aim, " \u00B7 ", e.contract.target] }), _jsx("span", { className: "label", style: { margin: 0 }, children: new Date(e.timestamp).toLocaleTimeString() })] })] }, e.delivery_id)))) })] }), _jsx("hr", { className: "divider" }), _jsxs("div", { className: "stack", style: { gap: 6 }, children: [_jsx("p", { className: "label", children: "Consent adherence" }), _jsx("div", { className: "row", style: { gap: 8 }, children: events.length > 0 ? (_jsxs(_Fragment, { children: [_jsxs("span", { className: "chip", children: ["State signals ", events[0].consent_scope.state_signals ? '✓' : '✗'] }), _jsxs("span", { className: "chip", children: ["Notifications ", events[0].consent_scope.notifications ? '✓' : '✗'] }), _jsxs("span", { className: "chip", children: ["Escalation ", events[0].consent_scope.escalation_contact ? '✓' : '✗'] })] })) : (_jsx("span", { className: "subtitle", style: { margin: 0 }, children: "No consent data." })) })] })] }) }));
};
