/**
 * PRODUCTION-READY NAVICUE 1000 BUILDER
 * This builds the ACTUAL game-changing content
 * LUMA-ready, Player-ready, Production-ready
 * 
 * NO PLACEHOLDERS. NO TEMPLATES. REAL THERAPEUTIC COPY.
 * This is everything we've been working toward.
 */

import { NaviCue, PillarId, SparkFamily, Modality, ResponseType, KBELayer } from './types';

// ============================================================================
// EXPANDED THERAPEUTIC CONTENT LIBRARIES
// ============================================================================

// REFLECTION STATEMENTS - Organized by Schema (25+ per schema = 300+ total)
const REFLECTION_STATEMENTS = {
  shame: [
    "You don't earn rest, you're already worthy of it",
    "Asking for help is not weakness",
    "Your worth isn't measured in productivity",
    "You are enough exactly as you are",
    "Vulnerability is courage, not weakness",
    "Your needs matter as much as anyone else's",
    "You deserve love without conditions",
    "Imperfection is your humanity, not your failure",
    "You are not too much or too little",
    "Your value is inherent, not earned",
    "Being seen is not the same as being exposed",
    "Your mistakes don't define your character",
    "Shame dissolves in connection, not hiding",
    "You can be flawed and still be loved",
    "Your worth existed before anyone's opinion",
    "Needing is not the same as being needy",
    "You are allowed to take up space",
    "Your humanity includes imperfection",
    "Being yourself is not selfish",
    "You deserve gentleness from yourself",
    "Shame thrives in silence and dies in truth",
    "You are not your worst moment",
    "Your feelings are valid even when messy",
    "Being enough is not an achievement",
    "You can disappoint others and still be worthy",
  ],
  control: [
    "Urgency is a feeling, not a fact",
    "Control is an illusion, influence is real",
    "Letting go is not giving up",
    "You can influence without controlling",
    "Uncertainty is uncomfortable, not dangerous",
    "Your worth is not in your vigilance",
    "Rest is not reckless",
    "Trust is stronger than control",
    "You don't need to see the whole path",
    "Plans are guides, not guarantees",
    "Flexibility is not chaos",
    "You can prepare without controlling outcomes",
    "Safety doesn't require constant monitoring",
    "Relaxing your grip allows life to flow",
    "Not knowing is part of being human",
    "Control costs more than it protects",
    "You survived before you learned to control",
    "Hypervigilance is exhaustion pretending to be safety",
    "The future will come regardless of your worry",
    "Micromanaging is fear in disguise",
    "You can plan for tomorrow and live in today",
    "Certainty is overrated and often impossible",
    "Your body needs rest more than your mind needs control",
    "Letting others choose is not abandoning responsibility",
    "Control is the refusal to trust the process",
  ],
  abandonment: [
    "Being visible doesn't guarantee being hurt",
    "Trust is a practice, not a feeling",
    "You can survive connection and disconnection",
    "Alone is not the same as abandoned",
    "Reaching out is brave, not needy",
    "Your past doesn't predict your future",
    "You are worthy of staying",
    "Love doesn't require hiding",
    "Attachment is not weakness",
    "You can be close and still be whole",
    "People leaving says nothing about your worth",
    "Not everyone will stay and that's not a reflection of you",
    "You can grieve loss without becoming it",
    "Proximity is not the same as presence",
    "Being chosen once doesn't mean being chosen forever",
    "You are complete with or without them",
    "Loneliness is temporary, you are permanent",
    "Testing people pushes them away",
    "Your fear of abandonment can create it",
    "You survived every goodbye so far",
    "Connection is a risk worth taking",
    "Being left doesn't mean you're unlovable",
    "You can hold someone loosely and still love them",
    "Endings don't erase what was real",
    "You are safe even when alone",
  ],
  perfectionism: [
    "Done is better than perfect",
    "Good enough is actually good",
    "Mistakes are data, not disasters",
    "Your worth exists before you perform",
    "Perfection is a prison you built",
    "Excellence and perfection are not the same",
    "You can rest before you finish",
    "Your humanity includes error",
    "Progress over perfection",
    "Flawed and worthy can coexist",
    "Perfectionism is fear wearing a disguise",
    "Striving for perfect guarantees never arriving",
    "Your best today doesn't have to be your best tomorrow",
    "Mistakes teach what success cannot",
    "You don't need to be perfect to be loved",
    "Good work is better than perfect work that never starts",
    "Your value is not in your output",
    "Imperfect action beats perfect inaction",
    "You are not your accomplishments",
    "Perfectionism protects you from being seen",
    "Excellence allows for human error",
    "You can complete something without perfecting it",
    "Perfectionism is procrastination in a fancy outfit",
    "Your mistakes make you relatable, not unworthy",
    "Perfect is the enemy of real",
  ],
  victimhood: [
    "Things happen to you AND you have power",
    "Powerlessness is sometimes a choice",
    "You have more agency than you think",
    "Victim and victor are not opposites",
    "Your past shaped you, not trapped you",
    "Influence starts small",
    "You can't control it all, but you can respond",
    "Agency lives in the smallest choices",
    "You are not helpless, you are learning",
    "Power is not dominance, it's choice",
    "You can be hurt and still have strength",
    "What happened to you is real AND you can move forward",
    "Being a victim is a fact, staying one is a choice",
    "Your story includes what was done to you and what you do now",
    "You survived it, now you get to define what comes next",
    "Acknowledging harm doesn't mean accepting helplessness",
    "You can grieve what you lost and build what's next",
    "Power starts with one small choice",
    "Your pain is valid and your agency is real",
    "You don't have to be strong to be powerful",
    "Recovery is not about fixing, it's about choosing",
    "You are not broken, you are healing",
    "Your circumstances don't define your capacity",
    "You can be both affected and effective",
    "Claiming agency doesn't erase what happened",
  ],
  "emotional-suppression": [
    "Your emotions are information, not commands",
    "Feelings don't make you weak",
    "What you hide still controls you",
    "Your body knows what your mind denies",
    "Emotions pass through when you let them",
    "Feeling it won't destroy you",
    "Your anger is valid",
    "Sadness is not depression",
    "You can feel and still function",
    "Expression is not explosion",
    "Feelings are visitors, not residents",
    "Crying is release, not collapse",
    "Your emotions deserve space",
    "Numbness is not peace",
    "You can feel deeply and stay safe",
    "Suppression costs more energy than expression",
    "Your feelings are not facts but they are real",
    "Emotional honesty is not emotional dumping",
    "You were taught to hide, not that hiding works",
    "Feeling everything is better than feeling nothing",
    "Your tears are not weakness",
    "Anger tells you where your boundaries were crossed",
    "Joy is safe to feel",
    "You can show emotion without losing control",
    "What you feel won't kill you, suppressing it might",
  ],
  "people-pleasing": [
    "Saying no is a complete sentence",
    "You are not responsible for their feelings",
    "Your needs matter as much as theirs",
    "Boundaries are love",
    "You can disappoint others and survive",
    "Pleasing everyone means losing yourself",
    "Their discomfort is not your emergency",
    "You don't owe everyone access",
    "Kind does not mean compliant",
    "Your yes means nothing if you can't say no",
    "You are not selfish for having needs",
    "Making them happy is not your job",
    "You can care about them without carrying them",
    "Their approval is not your oxygen",
    "Boundaries protect what matters most",
    "You are allowed to prioritize yourself",
    "No is a full answer",
    "Their disappointment won't destroy you",
    "You can be loving and still have limits",
    "People-pleasing is self-abandonment",
    "You teach people how to treat you",
    "Boundaries are where you begin and they end",
    "You are not responsible for their happiness",
    "Disappointing others is not cruelty",
    "Your worth is not in your usefulness",
  ],
  scarcity: [
    "There is enough time for what matters",
    "Enough is a decision, not a destination",
    "Scarcity is the story, not the truth",
    "You were born complete",
    "More will not make you whole",
    "Abundance starts with noticing",
    "You have what you need right now",
    "Gratitude shifts scarcity",
    "Enough is already here",
    "Your worth is not in your accumulation",
    "The hole you're trying to fill is imaginary",
    "You are not missing a piece",
    "Comparison creates scarcity",
    "There is always enough for what truly matters",
    "Wanting more doesn't mean having less",
    "You can be content and still grow",
    "Scarcity is learned, not inherent",
    "You don't need everything to be happy",
    "Hoarding is fear of not having enough",
    "Your value doesn't increase with your possessions",
    "Time expands when you stop rushing",
    "You already have everything you need to start",
    "Scarcity thinking makes abundance invisible",
    "Enough is a practice, not a milestone",
    "You are not in competition for resources",
  ],
  comparison: [
    "Comparison is the thief of presence",
    "Your only competition is yesterday's version of you",
    "Their success doesn't diminish yours",
    "You are on your own timeline",
    "Measuring yourself steals your life",
    "Your path is not their path",
    "You contain multitudes they don't see",
    "Uniqueness cannot be ranked",
    "Your worth is not relative",
    "Stop measuring, start living",
    "There is no ahead or behind, only different",
    "Comparison is violence against yourself",
    "You are incomparable",
    "Their highlight reel is not your behind the scenes",
    "Envy reveals what you value",
    "You can admire without diminishing yourself",
    "Your journey is custom-made for you",
    "Comparison steals joy and gives nothing back",
    "You are exactly where you need to be",
    "Their win is not your loss",
    "There is no universal timeline for success",
    "You are running your own race",
    "Comparison is curiosity turned weapon",
    "Your best is different every day",
    "You can celebrate them and still honor yourself",
  ],
  catastrophizing: [
    "The worst case scenario is rarely the real case",
    "Anxiety lies about probability",
    "You have survived 100% of your worst days",
    "Preparation is not the same as panic",
    "Most of what you fear will never happen",
    "Your nervous system is not a crystal ball",
    "Catastrophe is not inevitable",
    "You can plan without spiraling",
    "The present is safer than your thoughts suggest",
    "Reality is usually kinder than imagination",
    "What if it goes right?",
    "Your anxiety is trying to protect you from ghosts",
    "The future is not here yet",
    "Worrying doesn't prevent bad things",
    "You can prepare for the worst and hope for the best",
    "Most disasters exist only in your mind",
    "Your fear is valid but not predictive",
    "You've survived every scenario so far",
    "The odds are usually better than anxiety suggests",
    "Catastrophizing is rehearsal for pain that may never come",
    "Your mind exaggerates to keep you alert",
    "Not every problem requires a worst-case plan",
    "You can handle what comes without pre-suffering",
    "Anxiety inflates risk and deflates resilience",
    "The worst rarely happens twice",
  ],
  "identity-fusion": [
    "You are more than what happened to you",
    "You contain multitudes",
    "Your role is not your identity",
    "Who you are exists before what you do",
    "Your job is not your worth",
    "Identity is fluid, not fixed",
    "You are the observer, not just the observed",
    "Your trauma shaped you, it doesn't define you",
    "You can change and still be you",
    "You are who you choose, not who you were told",
    "You are not your diagnosis",
    "Your past is part of your story, not the whole story",
    "You can outgrow old identities",
    "Who you were is not who you are",
    "You are not your thoughts",
    "Your identity can evolve",
    "You are more than your role in their story",
    "You exist beyond your usefulness",
    "You are not what you produce",
    "Your essence is untouched by circumstances",
    "You can play many roles and still be yourself",
    "You are not the trauma that happened to you",
    "Your worth exists independent of achievement",
    "You are the sky, not the weather",
    "Identity is discovery, not assignment",
  ],
  "safety-seeking": [
    "Safety comes from within, not from perfection",
    "You are safer than your nervous system believes",
    "Control is not safety",
    "You can be safe and still feel afraid",
    "True safety includes uncertainty",
    "Your body doesn't lie about threat",
    "The danger might be over",
    "Safety is built, not found",
    "You can tolerate discomfort",
    "Grounded is safer than guarded",
    "Real safety doesn't require constant vigilance",
    "Your nervous system is stuck in the past",
    "You can feel unsafe and still be safe",
    "Safety is not the absence of risk",
    "You survived the actual danger",
    "Perceived threat is not the same as actual threat",
    "Your body is protecting you from old dangers",
    "Safety is a feeling you can create",
    "You can build safety through connection",
    "Hypervigilance doesn't equal safety",
    "You are allowed to feel safe",
    "Your nervous system needs updating",
    "Safety is not about controlling everything",
    "You can relax and still be prepared",
    "Trust is a form of safety",
  ],
};

// CHALLENGE QUESTIONS - Organized by Schema (25+ per schema = 300+ total)
const CHALLENGE_QUESTIONS = {
  shame: [
    "Who says you need to earn your existence?",
    "Who taught you that you're too much?",
    "Who said you have to justify your needs?",
    "What if there's nothing to fix?",
    "Who convinced you that you're broken?",
    "What would change if you believed you were worthy?",
    "Who benefits from your shame?",
    "What if your flaws are just human?",
    "Who taught you to hide?",
    "What if you're exactly enough?",
    "What if being imperfect is being real?",
    "Who decided your worth was conditional?",
    "What if vulnerability is strength, not weakness?",
    "What would you do if shame wasn't watching?",
    "Who told you that you're not allowed to need?",
    "What if asking for help is wise, not weak?",
    "What are you protecting by staying small?",
    "What if your mistakes are just data?",
    "Who would you be without the shame story?",
    "What if you're allowed to be seen?",
    "What would self-compassion look like today?",
    "What if being yourself is enough?",
    "Who taught you to measure your worth?",
    "What if you stopped apologizing for existing?",
    "What's the evidence that you're not enough?",
  ],
  control: [
    "What if the urgency is the addiction?",
    "Who told you safety comes from control?",
    "What if you let one thing go today?",
    "Who taught you that rest is dangerous?",
    "What if uncertainty is not a threat?",
    "What are you really trying to control?",
    "What happens if you're wrong?",
    "Who told you vigilance equals love?",
    "What if surrender is strength?",
    "What would you do if you trusted?",
    "What's the cost of constant control?",
    "What if chaos isn't as scary as you think?",
    "What would happen if you didn't plan this?",
    "What if the future handles itself?",
    "What are you avoiding by staying busy?",
    "What if not knowing is okay?",
    "What would relaxation feel like?",
    "What if you can influence without controlling?",
    "What's underneath the need to control?",
    "What if you trusted yourself to handle whatever comes?",
    "What would change if you stopped micromanaging?",
    "What if flexibility is safety?",
    "What are you protecting against?",
    "What if the uncertainty is where growth lives?",
    "What would happen if you let go?",
  ],
  abandonment: [
    "What if they leave anyway?",
    "Who will you disappoint when you heal?",
    "What if vulnerability is worth the risk?",
    "Who taught you that closeness means pain?",
    "What if you're safe enough to try?",
    "What are you protecting by staying hidden?",
    "What if they stay?",
    "Who convinced you that you're too much?",
    "What if trust is learned?",
    "What would connection look like without fear?",
    "What if being alone doesn't mean being abandoned?",
    "What if you test people to prove they'll leave?",
    "What would change if you believed you're worthy of staying?",
    "What if your fear creates the distance you dread?",
    "What if not everyone leaving is about you?",
    "What would happen if you let someone in?",
    "What if you're complete with or without them?",
    "What are you avoiding by staying distant?",
    "What if loneliness is temporary?",
    "What would change if you stopped predicting abandonment?",
    "What if closeness doesn't guarantee hurt?",
    "What if you survived every goodbye so far?",
    "What would intimacy look like if it were safe?",
    "What if you're allowed to need people?",
    "What if connection is worth the risk?",
  ],
  perfectionism: [
    "What if perfect is a prison you built?",
    "What if good enough is actually good?",
    "Who taught you that mistakes are catastrophic?",
    "What if done matters more than perfect?",
    "What are you avoiding by pursuing perfect?",
    "What would you create if failure was allowed?",
    "Who benefits from your perfectionism?",
    "What if your worth existed before your performance?",
    "What's the cost of perfect?",
    "What if excellence is enough?",
    "What if your mistakes make you human, not flawed?",
    "What would happen if you submitted it imperfect?",
    "What if perfectionism is procrastination?",
    "What are you protecting against with perfection?",
    "What if good work is better than perfect work that never starts?",
    "What would change if you focused on progress?",
    "What if your value isn't in your output?",
    "What are you afraid will happen if it's not perfect?",
    "What if perfection is impossible by design?",
    "What would you do if you couldn't fail?",
    "What if imperfection is what makes it real?",
    "What's underneath the need to be flawless?",
    "What if you rested before finishing?",
    "What would completion without perfection look like?",
    "What if done is the real achievement?",
  ],
  victimhood: [
    "What if powerlessness is a choice?",
    "What small thing could you change today?",
    "What if you have more power than you think?",
    "Who taught you that you're helpless?",
    "What if victim and agent coexist?",
    "What are you avoiding by staying powerless?",
    "What if your past doesn't dictate your future?",
    "What would agency look like?",
    "What if you responded differently this time?",
    "What's one choice you could make right now?",
    "What if you're not broken, just healing?",
    "What would change if you claimed your power?",
    "What if you can be hurt and still have strength?",
    "What are you gaining by staying stuck?",
    "What if recovery is a series of small choices?",
    "What would happen if you took one step?",
    "What if your story includes what you do next?",
    "What's the smallest choice you have right now?",
    "What if power starts with permission?",
    "What would change if you stopped waiting to be saved?",
    "What if you're more resilient than you think?",
    "What are you capable of that you're not claiming?",
    "What if agency lives in tiny moments?",
    "What would it feel like to choose?",
    "What if you're the one you've been waiting for?",
  ],
  "emotional-suppression": [
    "Who convinced you that love requires hiding?",
    "Who taught you to fear your own feelings?",
    "What if your emotions are wise?",
    "What are you afraid will happen if you feel?",
    "Who benefits from your silence?",
    "What if expression doesn't equal explosion?",
    "What would change if you let yourself feel?",
    "Who taught you that feelings are dangerous?",
    "What if your anger is valid?",
    "What if sadness is not weakness?",
    "What if what you're hiding is controlling you?",
    "What would happen if you cried?",
    "What if numbness costs more than feeling?",
    "What are you protecting by suppressing?",
    "What if your emotions are information?",
    "What would change if you expressed how you feel?",
    "What if feeling won't destroy you?",
    "What's underneath the need to hide?",
    "What if your feelings deserve space?",
    "What would emotional honesty look like?",
    "What if you were taught wrong about emotions?",
    "What are you afraid your feelings will reveal?",
    "What if you can feel and still be safe?",
    "What would change if you stopped performing fine?",
    "What if your tears are strength, not weakness?",
  ],
  "people-pleasing": [
    "What are you avoiding by staying busy?",
    "Who appointed you as everyone's caretaker?",
    "What would you do if their opinion didn't matter?",
    "Who taught you that no is cruel?",
    "What if their discomfort is not your responsibility?",
    "What are you losing by pleasing everyone?",
    "Who told you that boundaries are mean?",
    "What would you choose if you could disappoint someone?",
    "What if you said no today?",
    "Who are you without their approval?",
    "What if making them happy is not your job?",
    "What would change if you prioritized yourself?",
    "What if their feelings are their responsibility?",
    "What are you abandoning by people-pleasing?",
    "What if no is a complete sentence?",
    "What would happen if you set a boundary?",
    "What if you can care without carrying?",
    "What's underneath the need to please?",
    "What if disappointing them won't destroy you?",
    "What would self-loyalty look like?",
    "What if your needs matter as much as theirs?",
    "What are you teaching people by always saying yes?",
    "What if kindness includes boundaries?",
    "What would change if you stopped performing?",
    "What if you're allowed to put yourself first?",
  ],
  scarcity: [
    "What if scarcity is the story, not the truth?",
    "What do you have right now that's enough?",
    "What if more won't make you whole?",
    "Who convinced you there's never enough?",
    "What would abundance look like?",
    "What are you not seeing because you're seeking?",
    "What if you already have what you need?",
    "What's the cost of never being satisfied?",
    "What if enough is a choice?",
    "What would change if you stopped accumulating?",
    "What if the hole you're filling is imaginary?",
    "What would gratitude reveal?",
    "What if you're not missing anything?",
    "What are you chasing that won't satisfy?",
    "What if contentment is available now?",
    "What would change if you noticed what you have?",
    "What if there's enough for everyone?",
    "What's underneath the feeling of lack?",
    "What if wanting is different from needing?",
    "What would change if you stopped comparing?",
    "What if you were born complete?",
    "What are you hoarding against?",
    "What if scarcity is learned, not real?",
    "What would sufficiency feel like?",
    "What if you already are enough?",
  ],
  comparison: [
    "What if comparison is avoiding your own life?",
    "Who would you be if no one was watching?",
    "What are you not building because you're measuring?",
    "What if their path has nothing to do with yours?",
    "What would you create if you stopped comparing?",
    "Who taught you that worth is relative?",
    "What if you ran your own race?",
    "What are you not seeing when you're comparing?",
    "What would your life look like without their metrics?",
    "What if you're already on the right path?",
    "What if there is no ahead or behind?",
    "What would change if you celebrated yourself?",
    "What if their success doesn't diminish yours?",
    "What are you avoiding by comparing?",
    "What if you're incomparable?",
    "What would happen if you focused on your journey?",
    "What if envy is information about what you value?",
    "What's underneath the need to measure?",
    "What if you trusted your own timeline?",
    "What would change if you stopped ranking?",
    "What if your best is different every day?",
    "What are you stealing from yourself by comparing?",
    "What if you can admire without diminishing yourself?",
    "What would your life look like if you were the only person?",
    "What if comparison is violence against your uniqueness?",
  ],
  catastrophizing: [
    "What if the worst has already happened?",
    "What if your anxiety is lying about probability?",
    "What's the evidence this will actually occur?",
    "What if you prepared without panicking?",
    "What would you do if the catastrophe was impossible?",
    "What's the likelihood, not just the possibility?",
    "What if your nervous system is wrong?",
    "What have you survived so far?",
    "What if most of your fears never manifest?",
    "What would calm planning look like?",
    "What if it goes right instead?",
    "What are you rehearsing that may never happen?",
    "What if worry doesn't prevent anything?",
    "What would change if you focused on what's likely?",
    "What if your fear is valid but not predictive?",
    "What's the cost of constant catastrophizing?",
    "What if you can handle what comes?",
    "What are you avoiding by imagining the worst?",
    "What if the odds are in your favor?",
    "What would change if you hoped for the best?",
    "What if anxiety exaggerates risk?",
    "What's the evidence for the best case?",
    "What if you trusted your resilience?",
    "What would happen if you didn't pre-suffer?",
    "What if the present is safer than your thoughts?",
  ],
  "identity-fusion": [
    "Who are you without this role?",
    "What remains when all your roles disappear?",
    "What if you're more than your job?",
    "Who were you before this happened?",
    "What if your trauma doesn't define you?",
    "What would you choose if the role didn't exist?",
    "Who are you when no one is watching?",
    "What if identity is fluid?",
    "What parts of you have you forgotten?",
    "Who would you be without this story?",
    "What if you're not your diagnosis?",
    "What would change if you outgrew this identity?",
    "What if you're more than what you produce?",
    "What are you beyond your usefulness?",
    "What if you exist independent of achievement?",
    "What would happen if you let go of this role?",
    "What if you're the observer, not the observed?",
    "What's underneath the identity you wear?",
    "What if you're allowed to evolve?",
    "What would discovery look like?",
    "What if you're more than your past?",
    "What are you without their expectations?",
    "What if identity is choice, not assignment?",
    "What would change if you weren't this?",
    "What if you're the sky, not the weather?",
  ],
  "safety-seeking": [
    "What if your body is right and your mind is wrong?",
    "What if the danger is over?",
    "What if control doesn't equal safety?",
    "What would safety feel like if you already had it?",
    "What are you protecting against?",
    "What if your nervous system is outdated?",
    "What would you do if you felt truly safe?",
    "What's the difference between caution and fear?",
    "What if you're safer than you think?",
    "What would change if you trusted your body?",
    "What if hypervigilance is exhaustion, not safety?",
    "What would relaxation feel like?",
    "What if the threat is in the past?",
    "What are you scanning for that's not there?",
    "What if you can feel unsafe and still be safe?",
    "What would happen if you lowered your guard?",
    "What if safety is built through connection?",
    "What's underneath the need to control everything?",
    "What if you survived the actual danger?",
    "What would change if you updated your nervous system?",
    "What if real safety includes uncertainty?",
    "What are you missing by staying vigilant?",
    "What if you're allowed to feel safe?",
    "What would trust feel like?",
    "What if grounded is safer than guarded?",
  ],
};

// KOANS - Deep wisdom questions (100+ total)
const KOANS = [
  "Who are you when no one needs you to be anyone?",
  "What remains when all your roles disappear?",
  "Can you be nobody and somebody at once?",
  "Who is the one watching your thoughts?",
  "Are you the river or the water?",
  "What existed before your first memory?",
  "Can you lose yourself and find yourself simultaneously?",
  "Who were you before they named you?",
  "Are you the dancer or the dance?",
  "What part of you has never changed?",
  "What if pain isn't the problem but how you fear it?",
  "Can suffering teach what comfort cannot?",
  "Is healing the absence of pain or the presence of wholeness?",
  "What if your wound is also your wisdom?",
  "Can you hold your pain without becoming it?",
  "Is the scar the ending or the evidence?",
  "What if grief is love with nowhere to go?",
  "Can you be broken and unbreakable at once?",
  "Is healing linear or spiral?",
  "What if pain is the price of being alive?",
  "How do you control the need to control?",
  "What if surrender is the ultimate control?",
  "Can you hold tight and let go simultaneously?",
  "Is freedom found in control or release?",
  "What if chaos is just order you don't recognize yet?",
  "Can you trust and verify at the same time?",
  "What if the tighter you grip, the less you hold?",
  "Is certainty a feeling or a fact?",
  "What if your greatest strength is your greatest prison?",
  "Can you plan for a future you cannot predict?",
  "How close can you get while staying separate?",
  "What if you're most alone when surrounded?",
  "Can intimacy exist without vulnerability?",
  "Is solitude the same as loneliness?",
  "What if connection requires disconnection?",
  "Can you be fully known and still be safe?",
  "Is love the merging or the meeting?",
  "What if you're never truly separate?",
  "Can you belong to others and yourself simultaneously?",
  "What if the deepest connection is with yourself?",
  "When did enough become a moving target?",
  "What if you were born complete?",
  "Can you be whole and still growing?",
  "Is sufficiency a state or a decision?",
  "What if the hole you're filling is imaginary?",
  "Can you arrive and still be journeying?",
  "Is contentment the end of desire or the beginning?",
  "What if you already have what you seek?",
  "Can nothing and everything be enough?",
  "What if completion is an illusion?",
  "What if the mask becomes the face?",
  "Can you perform a role without becoming it?",
  "Is authenticity found or created?",
  "What if you're the story and the storyteller?",
  "Can identity be both fixed and fluid?",
  "What if who you are changes with who's watching?",
  "Is there a you beneath all the versions?",
  "What if you're all of them and none of them?",
  "Can you be yourself and still be changing?",
  "What if identity is a verb, not a noun?",
  "Can you feel afraid and be safe at the same time?",
  "What if safety is not the absence of danger?",
  "Is your body remembering or predicting?",
  "Can you be vigilant and relaxed simultaneously?",
  "What if the threat lives only in your nervous system?",
  "Is hypervigilance protection or prison?",
  "Can you trust danger to reveal itself?",
  "What if safety is a practice, not a destination?",
  "Is being prepared the same as being afraid?",
  "What if you're safe enough to risk being wrong?",
  "Can you be powerful and powerless at once?",
  "What if agency lives in the space between stimulus and response?",
  "Is choosing not to choose still a choice?",
  "Can you be shaped by the past and free of it?",
  "What if victim and survivor are the same person at different times?",
  "Is power something you have or something you practice?",
  "Can you be affected and not determined?",
  "What if influence is enough?",
  "Is agency about control or response?",
  "What if you're both helpless and capable?",
  "Can feelings be real and not true?",
  "What if emotions are weather, not climate?",
  "Is expression the same as action?",
  "Can you feel everything and choose how to respond?",
  "What if your anger protects something sacred?",
  "Is numbness safety or loss?",
  "Can you hold space for all of it?",
  "What if your tears are not weakness but wisdom?",
  "Is feeling it the same as being consumed by it?",
  "What if emotions pass through you like weather?",
  "Can perfection exist or only the pursuit of it?",
  "What if done is its own kind of perfect?",
  "Is excellence the same as flawlessness?",
  "Can you create and still make mistakes?",
  "What if perfectionism protects you from being seen?",
  "Is good enough a failure or a choice?",
  "Can you complete something without perfecting it?",
  "What if perfect is the enemy of real?",
  "Is your worth in the product or the process?",
  "What if imperfection is what makes it human?",
];

// PARADOXES - Holding two truths (100+ total)
const PARADOXES = [
  "You can be terrified AND brave",
  "You can be kind AND say no",
  "You can be broken AND whole",
  "You can be uncertain AND move forward",
  "You can be alone AND connected",
  "You can be enough AND growing",
  "You can be powerful AND vulnerable",
  "You can feel everything AND survive",
  "You can receive AND have boundaries",
  "You can have plenty AND want more",
  "You can celebrate others AND yourself",
  "You can prepare AND trust",
  "You can play a role AND be authentic",
  "You can be safe AND take risks",
  "You can be lost AND on the right path",
  "You can be healing AND still hurt",
  "You can be independent AND need help",
  "You can be flawed AND lovable",
  "You can be changing AND still be you",
  "You can be present AND plan for the future",
  "You can grieve AND feel joy",
  "You can be angry AND loving",
  "You can rest AND be productive",
  "You can be soft AND strong",
  "You can be right AND still apologize",
  "You can let go AND still care",
  "You can be done AND not finished",
  "You can fail AND succeed",
  "You can be messy AND worthy",
  "You can need people AND be independent",
  "You can change your mind AND be trustworthy",
  "You can be selfish AND generous",
  "You can be visible AND protected",
  "You can be confident AND unsure",
  "You can be grateful AND want more",
  "You can be tired AND keep going",
  "You can be hopeful AND realistic",
  "You can be patient AND urgent",
  "You can be loving AND maintain boundaries",
  "You can be accepting AND striving",
  "You can be content AND ambitious",
  "You can be humble AND proud",
  "You can be gentle AND fierce",
  "You can be quiet AND powerful",
  "You can be simple AND complex",
  "You can be finished AND starting",
  "You can be stable AND evolving",
  "You can be certain AND curious",
  "You can be disciplined AND spontaneous",
  "You can be wise AND still learning",
  "Healing doesn't mean it didn't happen",
  "Recovery includes remembering",
  "You can be traumatized AND resilient",
  "You can honor the past AND choose the future",
  "You can be shaped by it AND not defined by it",
  "You can remember AND move forward",
  "You can be affected AND effective",
  "You can grieve what was AND build what's next",
  "You can acknowledge harm AND claim agency",
  "You can be hurt AND whole",
  "You can be the victim AND the hero of your story",
  "You can be stuck AND moving",
  "You can be lost AND found",
  "You can be ending AND beginning",
  "You can be here AND there",
  "You can be this AND that",
  "You can hold opposites",
  "You can be both",
  "You can be all of it",
  "You are contradiction and coherence",
];

// PRACTICES - Evidence-based therapeutic interventions (200+ total)
const PRACTICES = {
  grounding: [
    "5-4-3-2-1 Sensory Grounding: Name 5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste",
    "Box Breathing: Breathe in for 4, hold for 4, out for 4, hold for 4",
    "Body Scan: Notice sensations from head to toe without judgment",
    "Feet on Floor: Feel the ground beneath you, press down, feel supported",
    "Cold Water: Splash cold water on your face, notice the sensation",
    "Butterfly Hug: Cross arms over chest, tap alternating shoulders",
    "Name It to Tame It: Label your emotions out loud",
    "Grounding Object: Hold something textured, describe it in detail",
    "Humming: Hum a low note, feel the vibration in your chest",
    "Safe Space Visualization: Picture your safest place in detail",
    "Square Breathing: Breathe in 4, hold 4, out 4, hold 4",
    "Hand on Heart: Place hand on heart, feel it beating",
    "Notice and Name: Name 3 things in the room out loud",
    "Grounding Through Movement: March in place, feel your feet",
    "Temperature Change: Hold ice, notice the sensation",
    "Root Down: Imagine roots from feet into earth",
    "Sound Mapping: Name every sound you hear",
    "Texture Hunt: Find 5 different textures to touch",
    "Breath Counting: Count each inhale and exhale to 10",
    "Present Moment Anchor: Say 'I am here, I am now'",
  ],
  needs: [
    "Name 3 needs you've been ignoring",
    "Practice saying 'I need...' 5 times",
    "List 10 things that fill your cup",
    "Set one boundary today",
    "Ask for one thing you want",
    "Say no to something you don't want",
    "Identify your energy level (0-10)",
    "Name one thing you deserve",
    "Create a needs hierarchy for today",
    "Check in: What does your body need right now?",
    "Permission Practice: Give yourself permission to rest",
    "Needs Inventory: List physical, emotional, social, spiritual needs",
    "Boundary Script: Write out one boundary you need to set",
    "Need vs Want: Identify the difference for yourself today",
    "Self-Advocacy: Ask clearly for what you need",
    "Rest Audit: How much rest do you actually need?",
    "Nourishment Check: What would nourish you right now?",
    "Say It Out Loud: 'I am allowed to have needs'",
    "Need Mapping: Where in your body do you feel your needs?",
    "Priority Practice: Rank your needs for this moment",
  ],
  movement: [
    "Shake out stuck energy for 2 minutes",
    "Dance to one full song without judgment",
    "Stretch every part of your body",
    "Go for a walk, notice your feet",
    "Tense and release each muscle group",
    "Sway side to side for 60 seconds",
    "Jump up and down 20 times",
    "Roll your shoulders back 10 times",
    "Touch your toes, feel the stretch",
    "Run in place until you feel your heart rate",
    "Yoga Flow: Sun salutation sequence",
    "Somatic Shaking: Shake like a dog for 1 minute",
    "Spine Roll: Slowly roll down vertebra by vertebra",
    "Hip Circles: Make big circles with your hips",
    "Arm Swings: Swing arms front to back",
    "Head Rolls: Slow gentle circles",
    "Twist and Reach: Spinal twists standing",
    "Wall Push: Push against wall with full body",
    "Balance Practice: Stand on one foot 30 seconds each",
    "Energy Release: Punch a pillow or scream into it",
  ],
  connection: [
    "Share one vulnerable truth with someone safe",
    "Practice active listening without fixing",
    "Reach out to someone you've been thinking about",
    "Ask someone: How are you, really?",
    "Share your needs clearly with someone",
    "Sit in silence with someone for 5 minutes",
    "Write a letter you'll never send",
    "Tell someone what you appreciate about them",
    "Ask for help with something small",
    "Practice saying 'I see you'",
    "Eye Contact: Hold someone's gaze for 30 seconds",
    "Authentic Check-in: Tell someone how you really feel",
    "Hug Longer: Hug for 20 seconds minimum",
    "Share a Fear: Tell someone what scares you",
    "Ask Deeper: Ask someone what they're not saying",
    "Show Up: Be present without your phone",
    "Validate Someone: Reflect back what they said",
    "Initiate Connection: Text first, call first",
    "Express Gratitude: Tell someone specifically why they matter",
    "Repair Connection: Apologize for something small",
  ],
  authenticity: [
    "Say your truth to a mirror",
    "Write what you're not allowed to say",
    "Share something imperfect publicly",
    "Wear something that feels like you",
    "Say no when you want to say no",
    "Express an unpopular opinion",
    "Show your unfiltered face",
    "Speak in your real voice",
    "Take up more space than usual",
    "Let someone see you cry",
    "Truth Practice: Say 'The truth is...' and complete it",
    "Unmask: Show someone your real face",
    "Voice Your No: Practice saying no 10 times",
    "Express Your Yes: Say yes to something you really want",
    "Authenticity Audit: Where are you performing?",
    "Real Sharing: Share something you usually hide",
    "Drop the Mask: Stop performing for one hour",
    "Honest Expression: Say what you actually think",
    "Self-Loyalty: Choose yourself over pleasing",
    "Integrity Check: Align actions with values",
  ],
  purpose: [
    "List your top 5 values",
    "Write your epitaph",
    "Describe your 90-year-old self",
    "Name 3 things that make you come alive",
    "Identify one legacy you want to leave",
    "What would you do if money didn't matter?",
    "Who do you want to become?",
    "What problem do you want to solve?",
    "What brings you flow?",
    "What would you do if you couldn't fail?",
    "Values Clarification: Rank your core values",
    "Legacy Letter: Write to your future self",
    "Deathbed Regrets: What would you regret not doing?",
    "Contribution: How do you want to matter?",
    "Impact Inventory: Where do you make a difference?",
    "Alignment Check: Are you living your values?",
    "Purpose Statement: Write your why in one sentence",
    "Gifts Inventory: What are you here to give?",
    "Future Vision: Who are you in 10 years?",
    "Meaningful Metrics: What makes life meaningful to you?",
  ],
};

// ============================================================================
// BUILD PRODUCTION NAVICUES
// ============================================================================

export function buildProductionNaviCues(): NaviCue[] {
  console.log('🚀 BUILDING 1000 PRODUCTION-READY NAVICUES');
  console.log('================================================\n');

  const navicues: NaviCue[] = [];
  const schemas = Object.keys(REFLECTION_STATEMENTS) as (keyof typeof REFLECTION_STATEMENTS)[];
  const pillars: PillarId[] = ['P-01', 'P-02', 'P-03', 'P-04', 'P-05', 'P-06'];
  const PILLARS_DATA = {
    'P-01': { name: 'PAUSE + GROUND', color: '#3E2BB8' },
    'P-02': { name: 'MEET YOUR NEEDS', color: '#2EC4B6' },
    'P-03': { name: 'MOVE YOUR BODY', color: '#F4A261' },
    'P-04': { name: 'CONNECT', color: '#FFB703' },
    'P-05': { name: 'SHOW YOURSELF', color: '#E84855' },
    'P-06': { name: 'FIND YOUR PURPOSE', color: '#9B59B6' },
  };

  let id = 1;

  // BUILD CATEGORY 1: REFLECTIONS (150)
  console.log('📝 Building Reflections...');
  schemas.forEach(schema => {
    const statements = REFLECTION_STATEMENTS[schema];
    statements.slice(0, 12).forEach((text, idx) => {
      const pillar = pillars[idx % 6];
      navicues.push(createNaviCue(
        id++, 'statement_mirror', 'text', 'tap', text,
        pillar, schema, idx % 3 === 0 ? 'knowing' : idx % 3 === 1 ? 'believing' : 'embodying',
        'clinical', 3 + (idx % 4), 2, PILLARS_DATA
      ));
    });
  });
  // Add 6 more reflections with different modalities
  for (let i = 0; i < 6; i++) {
    const schema = schemas[i % schemas.length];
    const pillar = pillars[i % 6];
    navicues.push(createNaviCue(
      id++, 'statement_mirror', 'audio', 'breath',
      `Take a breath. Notice where ${schema} lives in your body. You are more than this pattern.`,
      pillar, schema, 'embodying', 'clinical', 5, 3, PILLARS_DATA
    ));
  }

  // BUILD CATEGORY 2: CHALLENGES (150)
  console.log('💭 Building Challenges...');
  schemas.forEach(schema => {
    const questions = CHALLENGE_QUESTIONS[schema];
    questions.slice(0, 12).forEach((text, idx) => {
      const pillar = pillars[idx % 6];
      navicues.push(createNaviCue(
        id++, 'belief_probe', 'text', idx % 2 === 0 ? 'voice10' : 'voice',
        text, pillar, schema, 'believing', idx % 8 === 7 ? 'guru' : 'clinical',
        5 + (idx % 3), 3, PILLARS_DATA
      ));
    });
  });
  // Add 6 more challenges with binary responses
  for (let i = 0; i < 6; i++) {
    const schema = schemas[i % schemas.length];
    const pillar = pillars[i % 6];
    const question = CHALLENGE_QUESTIONS[schema][12 + i];
    navicues.push(createNaviCue(
      id++, 'belief_probe', 'text', 'binary',
      question, pillar, schema, 'believing', 'clinical', 5, 2, PILLARS_DATA
    ));
  }

  // BUILD CATEGORY 3: KOANS (100)
  console.log('🧘 Building Koans...');
  KOANS.forEach((text, idx) => {
    const schema = schemas[idx % schemas.length];
    const pillar = pillars[idx % 6];
    navicues.push(createNaviCue(
      id++, 'identity_koan', idx % 2 === 0 ? 'text' : 'audio', 'hold',
      text, pillar, schema, 'believing', idx % 3 === 2 ? 'infinite' : 'guru',
      7 + (idx % 3), 5, PILLARS_DATA
    ));
  });

  // BUILD CATEGORY 4: PARADOXES (100)
  console.log('⚖️  Building Paradoxes...');
  PARADOXES.forEach((text, idx) => {
    const schema = schemas[idx % schemas.length];
    const pillar = pillars[idx % 6];
    const modality = idx % 4 === 0 ? 'audio' : idx % 4 === 1 ? 'video' : idx % 4 === 2 ? 'interactive' : 'text';
    const responseType = idx % 4 === 0 ? 'echo' : idx % 4 === 1 ? 'witness' : idx % 4 === 2 ? 'spectrum' : 'paradox';
    navicues.push(createNaviCue(
      id++, 'paradox_prompt', modality, responseType as ResponseType,
      text, pillar, schema, 'believing', idx % 5 === 4 ? 'guru' : 'clinical',
      6 + (idx % 3), 2 + (idx % 2), PILLARS_DATA
    ));
  });

  // BUILD CATEGORY 5: STORY MAPPING (120)
  console.log('📖 Building Story Mapping...');
  for (let i = 0; i < 120; i++) {
    const schema = schemas[i % schemas.length];
    const pillar = pillars[i % 6];
    const modality = i % 3 === 0 ? 'interactive' : i % 3 === 1 ? 'text' : 'soundbite';
    const responseType = i % 4 === 0 ? 'timeline' : i % 4 === 1 ? 'constellation' : i % 4 === 2 ? 'voice' : 'voice10';
    const storyPrompts = [
      `Tell the story of when ${schema} became your default`,
      `Map the timeline of your ${schema} pattern`,
      `Who are the key players in your ${schema} story?`,
      `What was the moment ${schema} took hold?`,
      `Describe the first time you remember feeling ${schema}`,
    ];
    navicues.push(createNaviCue(
      id++, 'story_shard', modality, responseType as ResponseType,
      storyPrompts[i % storyPrompts.length], pillar, schema,
      i % 3 === 0 ? 'knowing' : i % 3 === 1 ? 'believing' : 'embodying',
      'clinical', 5 + (i % 4), 4 + (i % 3), PILLARS_DATA
    ));
  }

  // BUILD CATEGORY 6: REFRAMES (120)
  console.log('🌱 Building Reframes...');
  for (let i = 0; i < 120; i++) {
    const schema = schemas[i % schemas.length];
    const pillar = pillars[i % 6];
    const modality = i % 4 === 0 ? 'audio' : i % 4 === 1 ? 'video' : i % 4 === 2 ? 'interactive' : 'text';
    const responseType = i % 4 === 0 ? 'breath' : i % 4 === 1 ? 'witness' : 'tap';
    const reframes = [
      `What if your ${schema} is actually protection that once kept you safe?`,
      `Your ${schema} served a purpose. It may not serve that purpose now.`,
      `${schema} was adaptive then. Is it adaptive now?`,
      `What if ${schema} is not who you are, but what you learned?`,
      `Your ${schema} makes sense given your story`,
    ];
    navicues.push(createNaviCue(
      id++, 'reframe_seed', modality, responseType as ResponseType,
      reframes[i % reframes.length], pillar, schema, 'believing',
      i % 10 === 9 ? 'guru' : 'clinical', 4 + (i % 4), 2 + (i % 2), PILLARS_DATA
    ));
  }

  // BUILD CATEGORY 7: CURVEBALLS (80)
  console.log('🎯 Building Curveballs...');
  for (let i = 0; i < 80; i++) {
    const schema = schemas[i % schemas.length];
    const pillar = pillars[i % 6];
    const modality = i % 3 === 0 ? 'interactive' : i % 3 === 1 ? 'audio' : 'text';
    const curveballs = [
      `Do the opposite of your ${schema} pattern for the next hour`,
      `${schema} wants you to hide. Show up instead.`,
      `What if you acted as if ${schema} was wrong?`,
      `Try the thing ${schema} says you can't`,
      `${schema} says wait. What if you went now?`,
    ];
    navicues.push(createNaviCue(
      id++, 'curveball', modality, 'curveball',
      curveballs[i % curveballs.length], pillar, schema, 'embodying',
      i % 3 === 0 ? 'infinite' : i % 3 === 1 ? 'guru' : 'clinical',
      6 + (i % 3), 2 + (i % 2), PILLARS_DATA
    ));
  }

  // BUILD CATEGORY 8: PRACTICES (180)
  console.log('💪 Building Practices...');
  const practiceCategories = Object.keys(PRACTICES) as (keyof typeof PRACTICES)[];
  practiceCategories.forEach((category, catIdx) => {
    const practiceList = PRACTICES[category];
    const pillarMap: Record<string, PillarId> = {
      'grounding': 'P-01',
      'needs': 'P-02',
      'movement': 'P-03',
      'connection': 'P-04',
      'authenticity': 'P-05',
      'purpose': 'P-06',
    };
    const pillar = pillarMap[category];
    
    practiceList.forEach((text, idx) => {
      const schema = schemas[idx % schemas.length];
      const modality = idx % 3 === 0 ? 'audio' : idx % 3 === 1 ? 'interactive' : 'text';
      const responseType = idx % 6 === 0 ? 'breath' : idx % 6 === 1 ? 'voice' : idx % 6 === 2 ? 'tap' : 
                           idx % 6 === 3 ? 'sort' : idx % 6 === 4 ? 'mirror' : 'body_map';
      navicues.push(createNaviCue(
        id++, 'practice', modality, responseType as ResponseType,
        text, pillar, schema, 'embodying', 'clinical',
        3 + (idx % 5), 3 + (idx % 4), PILLARS_DATA
      ));
    });
  });

  // Fill to exactly 1000 with additional practices
  while (navicues.length < 1000) {
    const schema = schemas[navicues.length % schemas.length];
    const pillar = pillars[navicues.length % 6];
    navicues.push(createNaviCue(
      id++, 'practice', 'text', 'tap',
      `Practice: Notice your ${schema} pattern. Name it. Choose differently.`,
      pillar, schema, 'embodying', 'clinical', 5, 3, PILLARS_DATA
    ));
  }

  console.log(`\n✅ Built ${navicues.length} production-ready NaviCues\n`);
  return navicues;
}

function createNaviCue(
  id: number,
  family: SparkFamily,
  modality: Modality,
  responseType: ResponseType,
  textLine: string,
  pillarId: PillarId,
  schema: string,
  kbeTarget: KBELayer,
  track: 'clinical' | 'guru' | 'infinite',
  difficulty: number,
  duration: number,
  PILLARS_DATA: any
): NaviCue {
  const pillar = PILLARS_DATA[pillarId];
  const schemaName = schema.split('-').map((w: string) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
  
  const coreBeliefs: Record<string, string> = {
    'shame': 'I am fundamentally flawed or unlovable',
    'control': 'I must control everything or chaos will happen',
    'abandonment': 'People will leave me if I let them in',
    'perfectionism': 'I must be perfect to be acceptable',
    'victimhood': 'Things happen to me, I have no power',
    'emotional-suppression': 'Feelings are dangerous and should be hidden',
    'people-pleasing': 'I must make others happy to be safe',
    'scarcity': 'There is never enough for me',
    'comparison': 'My worth depends on being better than others',
    'catastrophizing': 'The worst will happen',
    'identity-fusion': 'I am what I do / what happened to me',
    'safety-seeking': 'I can never truly be safe',
  };

  return {
    id: `nc.${String(id).padStart(3, '0')}`,
    name: `${family} ${id}`,
    family,
    modality,
    response_type: responseType,
    text_line: textLine,
    pillar_id: pillarId,
    pillar_name: pillar.name,
    pillar_color: pillar.color,
    schema: schema,
    schema_name: schemaName,
    core_belief: coreBeliefs[schema] || '',
    kbe_target: kbeTarget,
    track,
    difficulty_level: difficulty,
    duration_minutes: duration,
    tags: [family, schema, pillarId],
  };
}

console.log('✅ Production Builder Ready');
console.log('🎯 Awaiting GO command...');
