/**
 * NAVICUE BATCH: JOURNEY + FEATURE INTEGRATION
 * 
 * Auto-generated NaviCues for:
 * 1. Journey Integration (Sprints 1-4, ERA framework)
 * 2. Platform Feature Showcase (Voice, Story, State, Articles, Practices, Mind Steps, Wellbeing)
 * 
 * Created: December 30, 2024
 * Total NaviCues: 120 (60 Journey + 60 Feature Integration)
 * 
 * Tags for filtering:
 * - journey_sprint_1, journey_sprint_2, journey_sprint_3, journey_sprint_4
 * - voice, story, state, articles, practices, mindsteps, wellbeing
 */

import { NaviCue } from '../types';

// ============================================================================
// JOURNEY NAVICUES (60 total - 15 per sprint)
// ============================================================================

// Sprint 1: From State to Self (Ground + Notice)
const JOURNEY_SPRINT_1: NaviCue[] = [
  {
    id: 'journey_s1_001',
    name: 'Sprint 1 Opening: Ground',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Right now, you are exactly where you need to be. Not behind. Not failing. Here.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Window of Tolerance',
    theme_name: 'Grounding',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_1', 'grounding', 'state'],
    intent_primary: 'Ground the user in present moment',
    voice_archetype: 'Gentle Guide',
  },
  {
    id: 'journey_s1_002',
    name: 'State Check-in: Energy',
    family: 'practice',
    modality: 'interactive',
    text_line: 'On a scale of 1-10, how would you describe your energy right now?',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Self-Awareness',
    theme_name: 'Energy Tracking',
    response_type: 'slider',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_1', 'state', 'energy'],
    intent_primary: 'Capture energy state',
  },
  {
    id: 'journey_s1_003',
    name: 'Notice Without Fixing',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'What if noticing your state was enough? You don\'t have to fix anything right now.',
    pillar_id: 'SC',
    pillar_name: 'Self Compassion',
    pillar_color: '#10B981',
    concept_name: 'Self-Acceptance',
    theme_name: 'Non-Judgment',
    response_type: 'binary',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_1', 'acceptance'],
    intent_primary: 'Challenge fixing impulse',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s1_004',
    name: 'Body Scan: Quick Ground',
    family: 'practice',
    modality: 'audio',
    text_line: 'Take 60 seconds. Notice your breath. Notice your body. That\'s all.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Somatic Awareness',
    theme_name: 'Body Scan',
    response_type: 'breath',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_1', 'practice', 'somatic', 'wellbeing'],
    intent_primary: 'Ground through body awareness',
    duration_minutes: 1,
  },
  {
    id: 'journey_s1_005',
    name: 'The State You\'re In',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'Your state is information, not identity. Activated ≠ broken.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'State vs Trait',
    theme_name: 'Temporary States',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_1', 'identity', 'mindsteps'],
    intent_primary: 'Separate state from identity',
    voice_archetype: 'Straight Shooter',
  },
  {
    id: 'journey_s1_006',
    name: 'Clarity Check: What\'s True?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Beneath the noise, what\'s one thing you know to be true right now?',
    pillar_id: 'CR',
    pillar_name: 'Constructive Responsibility',
    pillar_color: '#F59E0B',
    concept_name: 'Clarity',
    theme_name: 'Truth Detection',
    response_type: 'one_word',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_1', 'clarity', 'state'],
    intent_primary: 'Access clarity beneath activation',
  },
  {
    id: 'journey_s1_007',
    name: 'Connection: Who Sees You?',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Who in your life sees you — not just the version you perform?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Authentic Connection',
    theme_name: 'Being Seen',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_1', 'connection', 'voice'],
    intent_primary: 'Identify authentic relationships',
  },
  {
    id: 'journey_s1_008',
    name: 'Story Shard: The Pattern',
    family: 'story_shard',
    modality: 'text',
    text_line: 'There\'s a pattern here. You\'ve felt this before. What does it remind you of?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Pattern Recognition',
    theme_name: 'Life Themes',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_1', 'story', 'narrative'],
    intent_primary: 'Connect present to pattern',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s1_009',
    name: 'Reframe: What If It\'s Working?',
    family: 'reframe_seed',
    modality: 'text',
    text_line: 'What if your nervous system is doing exactly what it\'s supposed to do?',
    pillar_id: 'CR',
    pillar_name: 'Constructive Responsibility',
    pillar_color: '#F59E0B',
    concept_name: 'Reframing',
    theme_name: 'Function Not Dysfunction',
    response_type: 'binary',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_1', 'reframe'],
    intent_primary: 'Reframe activation as adaptive',
  },
  {
    id: 'journey_s1_010',
    name: 'Practice: Window of Tolerance',
    family: 'practice',
    modality: 'text',
    text_line: 'Notice: Are you in your window? Above it? Below it? Just notice.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Window of Tolerance',
    theme_name: 'State Awareness',
    response_type: 'spectrum',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_1', 'practice', 'state'],
    intent_primary: 'Assess arousal state',
  },
  {
    id: 'journey_s1_011',
    name: 'Insight: You Are Not Your State',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: Activated, anxious, low — these are states you move through, not who you are.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'State vs Identity',
    theme_name: 'Temporary Nature',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_1', 'mindsteps', 'articles'],
    intent_primary: 'Deliver core insight',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s1_012',
    name: 'Completion: What Did You Notice?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'As you finish Sprint 1, what\'s one thing you noticed about yourself?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Self-Awareness',
    theme_name: 'Integration',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_1', 'reflection', 'voice'],
    intent_primary: 'Integrate sprint learning',
  },
  {
    id: 'journey_s1_013',
    name: 'Anchor: Your Ground Point',
    family: 'practice',
    modality: 'text',
    text_line: 'What\'s one thing that helps you feel grounded? Name it.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Grounding Resources',
    theme_name: 'Anchors',
    response_type: 'one_word',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_1', 'practice', 'grounding'],
    intent_primary: 'Identify personal anchor',
  },
  {
    id: 'journey_s1_014',
    name: 'Bridge: From State to Self',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'You just moved from noticing your state to understanding it doesn\'t define you. That\'s the work.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Integration',
    theme_name: 'Progress Recognition',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_1', 'completion'],
    intent_primary: 'Acknowledge progress',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s1_015',
    name: 'Next: Sprint 2 Preview',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Sprint 2: Emotional Agility. You\'ll learn to move with your emotions, not against them.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Emotional Agility',
    theme_name: 'Preview',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_1', 'transition'],
    intent_primary: 'Preview next sprint',
  },
];

// Sprint 2: Emotional Agility (15 NaviCues)
const JOURNEY_SPRINT_2: NaviCue[] = [
  {
    id: 'journey_s2_001',
    name: 'Sprint 2 Opening: Feel It',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Emotions aren\'t problems to solve. They\'re information to feel.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Emotional Acceptance',
    theme_name: 'Feel Don\'t Fix',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_2', 'emotions'],
    intent_primary: 'Introduce emotional agility',
    voice_archetype: 'Straight Shooter',
  },
  {
    id: 'journey_s2_002',
    name: 'Name It: What Are You Feeling?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Name the emotion. Don\'t analyze it. Just name it.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Affect Labeling',
    theme_name: 'Naming Emotions',
    response_type: 'one_word',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_2', 'practice', 'emotions'],
    intent_primary: 'Practice affect labeling',
  },
  {
    id: 'journey_s2_003',
    name: 'The Emotion Has a Message',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'Every emotion is a messenger. What is this one trying to tell you?',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Emotional Intelligence',
    theme_name: 'Message Detection',
    response_type: 'voice10',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_2', 'voice', 'emotions'],
    intent_primary: 'Decode emotional message',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s2_004',
    name: 'Practice: Ride the Wave',
    family: 'practice',
    modality: 'text',
    text_line: 'Emotions are waves. They rise, peak, and pass. You don\'t have to do anything.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Urge Surfing',
    theme_name: 'Wave Riding',
    response_type: 'breath',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_2', 'practice', 'wellbeing'],
    intent_primary: 'Practice urge surfing',
    duration_minutes: 2,
  },
  {
    id: 'journey_s2_005',
    name: 'Story: The Time You Felt This Before',
    family: 'story_shard',
    modality: 'text',
    text_line: 'When was the first time you felt this exact feeling? What was happening?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Emotional Memory',
    theme_name: 'Origin Stories',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_2', 'story', 'narrative'],
    intent_primary: 'Connect present emotion to history',
  },
  {
    id: 'journey_s2_006',
    name: 'Reframe: Emotions Are Adaptive',
    family: 'reframe_seed',
    modality: 'text',
    text_line: 'What if this emotion is exactly what you need to feel right now?',
    pillar_id: 'CR',
    pillar_name: 'Constructive Responsibility',
    pillar_color: '#F59E0B',
    concept_name: 'Reframing',
    theme_name: 'Adaptive Function',
    response_type: 'binary',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_2', 'reframe'],
    intent_primary: 'Reframe emotion as adaptive',
  },
  {
    id: 'journey_s2_007',
    name: 'The Opposite of Suppression',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'What would it feel like to not push this emotion away?',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Emotional Acceptance',
    theme_name: 'Non-Suppression',
    response_type: 'voice10',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_2', 'voice'],
    intent_primary: 'Explore non-suppression',
  },
  {
    id: 'journey_s2_008',
    name: 'Insight: Feelings Aren\'t Facts',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: Feeling anxious doesn\'t mean you\'re in danger. Feeling sad doesn\'t mean it\'s forever.',
    pillar_id: 'CR',
    pillar_name: 'Constructive Responsibility',
    pillar_color: '#F59E0B',
    concept_name: 'Cognitive Defusion',
    theme_name: 'Feelings vs Facts',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_2', 'mindsteps', 'articles'],
    intent_primary: 'Separate feelings from facts',
    voice_archetype: 'Straight Shooter',
  },
  {
    id: 'journey_s2_009',
    name: 'Connection: Who Can Hold This?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Is there someone in your life who can hold space for this feeling with you?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Co-Regulation',
    theme_name: 'Emotional Support',
    response_type: 'binary',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_2', 'connection'],
    intent_primary: 'Identify emotional support',
  },
  {
    id: 'journey_s2_010',
    name: 'Practice: RAIN Technique',
    family: 'practice',
    modality: 'text',
    text_line: 'Recognize. Allow. Investigate. Nurture. Try it with this emotion.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Mindfulness Practice',
    theme_name: 'RAIN',
    response_type: 'breath',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_2', 'practice', 'mindfulness', 'wellbeing'],
    intent_primary: 'Teach RAIN technique',
    duration_minutes: 3,
  },
  {
    id: 'journey_s2_011',
    name: 'The Emotion Wants to Move',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'E-motion. Energy in motion. It\'s designed to move through you, not stay stuck.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Emotional Flow',
    theme_name: 'Movement',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_2', 'mindsteps'],
    intent_primary: 'Teach emotional movement',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s2_012',
    name: 'What Does This Emotion Need?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'If this emotion could speak, what would it ask for?',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Emotional Needs',
    theme_name: 'Need Detection',
    response_type: 'voice10',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_2', 'voice'],
    intent_primary: 'Identify emotional need',
  },
  {
    id: 'journey_s2_013',
    name: 'Completion: What Did You Learn?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'You just practiced being with your emotions instead of fighting them. What changed?',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Integration',
    theme_name: 'Learning',
    response_type: 'voice10',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_2', 'reflection', 'voice'],
    intent_primary: 'Integrate sprint learning',
  },
  {
    id: 'journey_s2_014',
    name: 'Anchor: Your Emotion Resource',
    family: 'practice',
    modality: 'text',
    text_line: 'What helps you stay present with difficult emotions? Name your resource.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Resources',
    theme_name: 'Emotional Anchors',
    response_type: 'one_word',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_2', 'practice'],
    intent_primary: 'Identify emotional resource',
  },
  {
    id: 'journey_s2_015',
    name: 'Next: Sprint 3 Preview',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Sprint 3: Identity Work. You\'ll explore who you are beneath the roles you play.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Identity',
    theme_name: 'Preview',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_2', 'transition'],
    intent_primary: 'Preview next sprint',
  },
];

// Sprint 3: Identity Work (15 NaviCues)
const JOURNEY_SPRINT_3: NaviCue[] = [
  {
    id: 'journey_s3_001',
    name: 'Sprint 3 Opening: Who Are You?',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'Who are you when no one is watching?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Core Identity',
    theme_name: 'Self-Discovery',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_3', 'identity', 'voice'],
    intent_primary: 'Introduce identity work',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s3_002',
    name: 'The Roles You Play',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Parent. Partner. Professional. Friend. Which roles feel most like "you"?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Role Identity',
    theme_name: 'Role Awareness',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_3', 'identity', 'voice'],
    intent_primary: 'Explore role identity',
  },
  {
    id: 'journey_s3_003',
    name: 'Who You\'re Not',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'Sometimes knowing who you\'re not is as important as knowing who you are.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Identity Clarity',
    theme_name: 'Negative Space',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_3', 'identity', 'mindsteps'],
    intent_primary: 'Explore what you\'re not',
    voice_archetype: 'Straight Shooter',
  },
  {
    id: 'journey_s3_004',
    name: 'Story: The Person You Used to Be',
    family: 'story_shard',
    modality: 'text',
    text_line: 'Who were you before addiction? What parts of that person are still here?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Identity Continuity',
    theme_name: 'Past Self',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_3', 'story', 'narrative', 'voice'],
    intent_primary: 'Connect to past identity',
  },
  {
    id: 'journey_s3_005',
    name: 'Values: What Matters Most?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'If you could only pass on three values to someone you love, what would they be?',
    pillar_id: 'DM',
    pillar_name: 'Developing Meaning',
    pillar_color: '#EC4899',
    concept_name: 'Values',
    theme_name: 'Core Values',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_3', 'values', 'voice'],
    intent_primary: 'Identify core values',
  },
  {
    id: 'journey_s3_006',
    name: 'The Identity Gap',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: The gap between who you are and who you want to be — that\'s where growth happens.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Identity Development',
    theme_name: 'Growth Zone',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_3', 'mindsteps', 'articles'],
    intent_primary: 'Reframe identity gap as growth',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s3_007',
    name: 'Practice: Mirror Meditation',
    family: 'practice',
    modality: 'text',
    text_line: 'Look at yourself in a mirror for 60 seconds. Who do you see?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Self-Perception',
    theme_name: 'Mirror Work',
    response_type: 'mirror',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_3', 'practice', 'wellbeing'],
    intent_primary: 'Practice mirror meditation',
    duration_minutes: 1,
  },
  {
    id: 'journey_s3_008',
    name: 'Reframe: You Are Not Your Past',
    family: 'reframe_seed',
    modality: 'text',
    text_line: 'What if your past actions don\'t define your present identity?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Identity Flexibility',
    theme_name: 'Past Not Future',
    response_type: 'binary',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_3', 'reframe'],
    intent_primary: 'Separate past from identity',
  },
  {
    id: 'journey_s3_009',
    name: 'Connection: Who Knows the Real You?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Who sees you without the mask? Who knows your full story?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Authentic Connection',
    theme_name: 'Being Known',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_3', 'connection', 'voice'],
    intent_primary: 'Identify authentic witnesses',
  },
  {
    id: 'journey_s3_010',
    name: 'The Person You\'re Becoming',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'You\'re not stuck being who you were. You\'re actively becoming someone new.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Identity Growth',
    theme_name: 'Becoming',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_3', 'identity', 'mindsteps'],
    intent_primary: 'Emphasize identity evolution',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s3_011',
    name: 'Practice: Identity Constellation',
    family: 'practice',
    modality: 'interactive',
    text_line: 'Map the different parts of yourself. Which parts are in conflict? Which work together?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Internal Family Systems',
    theme_name: 'Parts Work',
    response_type: 'constellation',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_3', 'practice'],
    intent_primary: 'Map internal parts',
  },
  {
    id: 'journey_s3_012',
    name: 'Story: Your Origin',
    family: 'story_shard',
    modality: 'text',
    text_line: 'What\'s the story you tell yourself about where you come from?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Narrative Identity',
    theme_name: 'Origin Story',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_3', 'story', 'narrative', 'voice'],
    intent_primary: 'Explore origin narrative',
  },
  {
    id: 'journey_s3_013',
    name: 'Completion: Who Did You Discover?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'You\'ve been exploring your identity. What surprised you?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Self-Discovery',
    theme_name: 'Integration',
    response_type: 'voice10',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_3', 'reflection', 'voice'],
    intent_primary: 'Integrate sprint learning',
  },
  {
    id: 'journey_s3_014',
    name: 'Anchor: Your Core Truth',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'Beneath all the roles and stories, what\'s one truth about who you are?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Core Self',
    theme_name: 'Essential Identity',
    response_type: 'one_word',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_3', 'practice'],
    intent_primary: 'Identify core truth',
  },
  {
    id: 'journey_s3_015',
    name: 'Next: Sprint 4 Preview',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Sprint 4: Relational Capacity. You\'ll learn how to show up authentically in your relationships.',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Relationships',
    theme_name: 'Preview',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_3', 'transition'],
    intent_primary: 'Preview next sprint',
  },
];

// Sprint 4: Relational Capacity (15 NaviCues)
const JOURNEY_SPRINT_4: NaviCue[] = [
  {
    id: 'journey_s4_001',
    name: 'Sprint 4 Opening: Connection Is Medicine',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'You don\'t heal in isolation. You heal in connection.',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Healing Through Connection',
    theme_name: 'Relational Healing',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_4', 'connection'],
    intent_primary: 'Introduce relational healing',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s4_002',
    name: 'Attachment: Your Pattern',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Do you move toward people, away from them, or a mix of both?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Attachment Style',
    theme_name: 'Patterns',
    response_type: 'spectrum',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_4', 'attachment', 'mindsteps'],
    intent_primary: 'Identify attachment pattern',
  },
  {
    id: 'journey_s4_003',
    name: 'Practice: Boundaries',
    family: 'practice',
    modality: 'text',
    text_line: 'Say it out loud: "I can say no without losing love." How does that feel?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Boundaries',
    theme_name: 'Boundary Practice',
    response_type: 'voice10',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_4', 'practice', 'voice'],
    intent_primary: 'Practice boundary assertion',
  },
  {
    id: 'journey_s4_004',
    name: 'Story: The Relationship That Shaped You',
    family: 'story_shard',
    modality: 'text',
    text_line: 'Which relationship taught you the most about yourself? What did you learn?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Relational Learning',
    theme_name: 'Formative Relationships',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_4', 'story', 'narrative', 'voice'],
    intent_primary: 'Explore formative relationship',
  },
  {
    id: 'journey_s4_005',
    name: 'Vulnerability: The Risk',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'What makes it hard for you to be vulnerable?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Vulnerability',
    theme_name: 'Barriers',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_4', 'vulnerability', 'voice'],
    intent_primary: 'Explore vulnerability barriers',
  },
  {
    id: 'journey_s4_006',
    name: 'Insight: Connection Requires Risk',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: Real connection requires showing parts of yourself you usually hide.',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Authentic Connection',
    theme_name: 'Vulnerability Requirement',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_4', 'mindsteps', 'articles'],
    intent_primary: 'Teach vulnerability principle',
    voice_archetype: 'Straight Shooter',
  },
  {
    id: 'journey_s4_007',
    name: 'Reframe: Alone vs Lonely',
    family: 'reframe_seed',
    modality: 'text',
    text_line: 'What if being alone is okay, but loneliness is the signal to reach out?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Solitude vs Loneliness',
    theme_name: 'Distinction',
    response_type: 'binary',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_4', 'reframe'],
    intent_primary: 'Distinguish solitude from loneliness',
  },
  {
    id: 'journey_s4_008',
    name: 'Practice: Reach Out',
    family: 'practice',
    modality: 'text',
    text_line: 'Think of one person you trust. Send them a message right now. Just say hi.',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Connection Initiation',
    theme_name: 'Reaching Out',
    response_type: 'tap',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_4', 'practice', 'connection'],
    intent_primary: 'Practice connection initiation',
  },
  {
    id: 'journey_s4_009',
    name: 'The People Who See You',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Name three people who truly see you. What makes them safe?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Safe Relationships',
    theme_name: 'Witness Identification',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['journey', 'journey_sprint_4', 'connection', 'voice'],
    intent_primary: 'Identify safe witnesses',
  },
  {
    id: 'journey_s4_010',
    name: 'Rupture and Repair',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'Every relationship ruptures. What matters is whether you repair.',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Repair',
    theme_name: 'Relational Resilience',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_4', 'mindsteps'],
    intent_primary: 'Teach repair principle',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'journey_s4_011',
    name: 'Story: When Someone Showed Up',
    family: 'story_shard',
    modality: 'text',
    text_line: 'When was a time someone showed up for you when you needed them? What did they do?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Support Memory',
    theme_name: 'Being Held',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_4', 'story', 'narrative', 'voice'],
    intent_primary: 'Recall support memory',
  },
  {
    id: 'journey_s4_012',
    name: 'Practice: Gratitude Message',
    family: 'practice',
    modality: 'text',
    text_line: 'Send a gratitude message to someone who\'s been there for you. Be specific.',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Gratitude',
    theme_name: 'Appreciation Practice',
    response_type: 'tap',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_4', 'practice', 'gratitude'],
    intent_primary: 'Practice relational gratitude',
  },
  {
    id: 'journey_s4_013',
    name: 'Completion: What Changed?',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'You\'ve been exploring connection. What feels different about how you show up?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Relational Growth',
    theme_name: 'Integration',
    response_type: 'voice10',
    kbe_target: 'believing',
    tags: ['journey', 'journey_sprint_4', 'reflection', 'voice'],
    intent_primary: 'Integrate sprint learning',
  },
  {
    id: 'journey_s4_014',
    name: 'Anchor: Your Connection Commitment',
    family: 'practice',
    modality: 'text',
    text_line: 'What\'s one thing you\'ll do differently in your relationships moving forward?',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Commitment',
    theme_name: 'Relational Commitment',
    response_type: 'voice10',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_4', 'practice', 'voice'],
    intent_primary: 'Make relational commitment',
  },
  {
    id: 'journey_s4_015',
    name: 'Journey Complete',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'You\'ve moved from state to self to connection. You\'ve done the work. Keep going.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Journey Completion',
    theme_name: 'Acknowledgment',
    response_type: 'tap',
    kbe_target: 'embodying',
    tags: ['journey', 'journey_sprint_4', 'completion'],
    intent_primary: 'Acknowledge journey completion',
    voice_archetype: 'Wise Companion',
  },
];

// ============================================================================
// PLATFORM FEATURE INTEGRATION NAVICUES (60 total - ~8-10 per feature)
// ============================================================================

// Feature 1: Voice Showcase (10 NaviCues)
const FEATURE_VOICE: NaviCue[] = [
  {
    id: 'feature_voice_001',
    name: 'Voice Demo: Wise Companion',
    family: 'statement_mirror',
    modality: 'audio',
    text_line: 'Sometimes the kindest thing you can do is pause and ask: What do I need right now?',
    pillar_id: 'SC',
    pillar_name: 'Self Compassion',
    pillar_color: '#10B981',
    concept_name: 'Self-Care',
    theme_name: 'Needs Awareness',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['feature', 'voice', 'wise_companion', 'demo'],
    intent_primary: 'Showcase Wise Companion voice',
    voice_archetype: 'Wise Companion',
  },
  {
    id: 'feature_voice_002',
    name: 'Voice Demo: Straight Shooter',
    family: 'statement_mirror',
    modality: 'audio',
    text_line: 'You know what you need to do. The question is: are you going to do it?',
    pillar_id: 'DM',
    pillar_name: 'Developing Meaning',
    pillar_color: '#EC4899',
    concept_name: 'Action',
    theme_name: 'Follow-Through',
    response_type: 'binary',
    kbe_target: 'believing',
    tags: ['feature', 'voice', 'straight_shooter', 'demo'],
    intent_primary: 'Showcase Straight Shooter voice',
    voice_archetype: 'Straight Shooter',
  },
  {
    id: 'feature_voice_003',
    name: 'Voice Demo: Gentle Guide',
    family: 'practice',
    modality: 'audio',
    text_line: 'Let\'s take this slowly. There\'s no rush. Just breathe with me.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Pacing',
    theme_name: 'Gentle Approach',
    response_type: 'breath',
    kbe_target: 'embodying',
    tags: ['feature', 'voice', 'gentle_guide', 'demo', 'wellbeing'],
    intent_primary: 'Showcase Gentle Guide voice',
    voice_archetype: 'Gentle Guide',
    duration_minutes: 1,
  },
  {
    id: 'feature_voice_004',
    name: 'Voice Demo: Playful Provocateur',
    family: 'curveball',
    modality: 'audio',
    text_line: 'What if the thing you\'re afraid of is actually the thing that sets you free?',
    pillar_id: 'CR',
    pillar_name: 'Constructive Responsibility',
    pillar_color: '#F59E0B',
    concept_name: 'Reframing',
    theme_name: 'Paradox',
    response_type: 'binary',
    kbe_target: 'believing',
    tags: ['feature', 'voice', 'playful_provocateur', 'demo'],
    intent_primary: 'Showcase Playful Provocateur voice',
    voice_archetype: 'Playful Provocateur',
  },
  {
    id: 'feature_voice_005',
    name: 'Voice Response: 10-Second',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Tell me in 10 seconds: What\'s the real issue here?',
    pillar_id: 'CR',
    pillar_name: 'Constructive Responsibility',
    pillar_color: '#F59E0B',
    concept_name: 'Clarity',
    theme_name: 'Core Issue',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['feature', 'voice', 'response', 'demo'],
    intent_primary: 'Demo voice10 response type',
  },
  {
    id: 'feature_voice_006',
    name: 'Voice Response: Full Voice',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'Take all the time you need. Tell me your story.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Narrative',
    theme_name: 'Story Telling',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['feature', 'voice', 'response', 'demo', 'story'],
    intent_primary: 'Demo voice response type',
  },
  {
    id: 'feature_voice_007',
    name: 'Voice Archetype: Contextual Switching',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Notice how the voice changes based on what you need. That\'s intentional.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Adaptive Support',
    theme_name: 'Voice Flexibility',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['feature', 'voice', 'demo', 'mindsteps'],
    intent_primary: 'Explain voice system',
  },
  {
    id: 'feature_voice_008',
    name: 'Voice Integration: LUMA Pairing',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'LUMA learns which voice you respond to best. The system adapts to you.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Personalization',
    theme_name: 'Adaptive System',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'voice', 'demo', 'luma'],
    intent_primary: 'Explain LUMA voice pairing',
  },
  {
    id: 'feature_voice_009',
    name: 'Voice: Echo Response',
    family: 'practice',
    modality: 'audio',
    text_line: 'Repeat after me: I am enough. Say it out loud.',
    pillar_id: 'SC',
    pillar_name: 'Self Compassion',
    pillar_color: '#10B981',
    concept_name: 'Affirmation',
    theme_name: 'Echo Practice',
    response_type: 'echo',
    kbe_target: 'embodying',
    tags: ['feature', 'voice', 'demo', 'practice'],
    intent_primary: 'Demo echo response type',
  },
  {
    id: 'feature_voice_010',
    name: 'Voice: Witness Mode',
    family: 'practice',
    modality: 'audio',
    text_line: 'I\'m here. I\'m listening. Take your time.',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Witnessing',
    theme_name: 'Being Heard',
    response_type: 'witness',
    kbe_target: 'embodying',
    tags: ['feature', 'voice', 'demo', 'practice'],
    intent_primary: 'Demo witness response type',
  },
];

// Feature 2: Story Integration (10 NaviCues)
const FEATURE_STORY: NaviCue[] = [
  {
    id: 'feature_story_001',
    name: 'Story Shard: Pattern Recognition',
    family: 'story_shard',
    modality: 'text',
    text_line: 'This moment feels familiar. When else have you felt this way?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Pattern Recognition',
    theme_name: 'Déjà Vu',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['feature', 'story', 'narrative', 'demo'],
    intent_primary: 'Demo story shard linking',
  },
  {
    id: 'feature_story_002',
    name: 'Story: The Before Story',
    family: 'story_shard',
    modality: 'text',
    text_line: 'Who were you before this? What parts of that person are still here?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Identity Continuity',
    theme_name: 'Pre-Addiction Self',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['feature', 'story', 'narrative', 'demo'],
    intent_primary: 'Explore pre-addiction narrative',
  },
  {
    id: 'feature_story_003',
    name: 'Story: The Turning Point',
    family: 'story_shard',
    modality: 'text',
    text_line: 'Every story has a moment when everything changes. What was yours?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Narrative Arc',
    theme_name: 'Pivot Moment',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['feature', 'story', 'narrative', 'demo'],
    intent_primary: 'Identify turning point',
  },
  {
    id: 'feature_story_004',
    name: 'Story: Origin Wound',
    family: 'story_shard',
    modality: 'text',
    text_line: 'Where did this pattern begin? What\'s the earliest memory?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Origin Story',
    theme_name: 'First Memory',
    response_type: 'voice',
    kbe_target: 'believing',
    tags: ['feature', 'story', 'narrative', 'demo'],
    intent_primary: 'Explore origin memory',
  },
  {
    id: 'feature_story_005',
    name: 'Story: Rewrite Your Narrative',
    family: 'story_shard',
    modality: 'text',
    text_line: 'You\'re not stuck in one story. You can tell it differently.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Narrative Flexibility',
    theme_name: 'Story Revision',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'story', 'narrative', 'demo', 'mindsteps'],
    intent_primary: 'Teach narrative flexibility',
  },
  {
    id: 'feature_story_006',
    name: 'Story: Timeline Exercise',
    family: 'practice',
    modality: 'interactive',
    text_line: 'Map your story on a timeline. Where are the highs? The lows? The turning points?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Life Review',
    theme_name: 'Timeline Mapping',
    response_type: 'timeline',
    kbe_target: 'embodying',
    tags: ['feature', 'story', 'narrative', 'demo', 'practice'],
    intent_primary: 'Demo timeline response type',
  },
  {
    id: 'feature_story_007',
    name: 'Story: The Chapter You\'re In',
    family: 'story_shard',
    modality: 'text',
    text_line: 'If your life were a book, what chapter are you in right now?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Present Moment',
    theme_name: 'Current Chapter',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['feature', 'story', 'narrative', 'demo', 'voice'],
    intent_primary: 'Frame present as chapter',
  },
  {
    id: 'feature_story_008',
    name: 'Story: Future Self Letter',
    family: 'practice',
    modality: 'text',
    text_line: 'Write a letter to your future self. What do you want them to know?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Future Orientation',
    theme_name: 'Letter Writing',
    response_type: 'voice',
    kbe_target: 'embodying',
    tags: ['feature', 'story', 'narrative', 'demo', 'practice', 'voice'],
    intent_primary: 'Demo letter writing practice',
  },
  {
    id: 'feature_story_009',
    name: 'Story: The Story You Tell Others',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'How do you introduce yourself? What story do you tell?',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Public Narrative',
    theme_name: 'Self-Presentation',
    response_type: 'voice10',
    kbe_target: 'knowing',
    tags: ['feature', 'story', 'narrative', 'demo', 'voice'],
    intent_primary: 'Explore public narrative',
  },
  {
    id: 'feature_story_010',
    name: 'Story Integration: LUMA Linking',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'LUMA connects your story shards across time. The system sees your patterns.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Pattern Recognition',
    theme_name: 'System Intelligence',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'story', 'demo', 'luma', 'mindsteps'],
    intent_primary: 'Explain story linking system',
  },
];

// Feature 3: State Check-ins (8 NaviCues)
const FEATURE_STATE: NaviCue[] = [
  {
    id: 'feature_state_001',
    name: 'State: Energy Check',
    family: 'practice',
    modality: 'interactive',
    text_line: 'On a scale of 1-10, how is your energy right now?',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'State Awareness',
    theme_name: 'Energy',
    response_type: 'slider',
    kbe_target: 'knowing',
    tags: ['feature', 'state', 'checkin', 'demo', 'energy'],
    intent_primary: 'Demo energy slider',
  },
  {
    id: 'feature_state_002',
    name: 'State: Clarity Check',
    family: 'practice',
    modality: 'interactive',
    text_line: 'How clear is your thinking? 1 = foggy, 10 = crystal clear',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'State Awareness',
    theme_name: 'Clarity',
    response_type: 'slider',
    kbe_target: 'knowing',
    tags: ['feature', 'state', 'checkin', 'demo', 'clarity'],
    intent_primary: 'Demo clarity slider',
  },
  {
    id: 'feature_state_003',
    name: 'State: Connection Check',
    family: 'practice',
    modality: 'interactive',
    text_line: 'How connected do you feel right now? 1 = isolated, 10 = deeply connected',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Connection Awareness',
    theme_name: 'Connection',
    response_type: 'slider',
    kbe_target: 'knowing',
    tags: ['feature', 'state', 'checkin', 'demo', 'connection'],
    intent_primary: 'Demo connection slider',
  },
  {
    id: 'feature_state_004',
    name: 'State: 3D Check-in',
    family: 'practice',
    modality: 'interactive',
    text_line: 'Energy · Clarity · Connection. Rate all three.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Comprehensive State',
    theme_name: '3D Awareness',
    response_type: 'dial',
    kbe_target: 'knowing',
    tags: ['feature', 'state', 'checkin', 'demo', '3d'],
    intent_primary: 'Demo 3D check-in',
  },
  {
    id: 'feature_state_005',
    name: 'State: Arousal Spectrum',
    family: 'practice',
    modality: 'interactive',
    text_line: 'Are you in your window? Above it (activated)? Below it (shutdown)?',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Window of Tolerance',
    theme_name: 'Arousal State',
    response_type: 'spectrum',
    kbe_target: 'knowing',
    tags: ['feature', 'state', 'checkin', 'demo', 'arousal'],
    intent_primary: 'Demo arousal spectrum',
  },
  {
    id: 'feature_state_006',
    name: 'State: Trend Tracking',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Your state data creates patterns. LUMA sees when you need support before you do.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Predictive Support',
    theme_name: 'Pattern Detection',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'state', 'demo', 'luma', 'mindsteps'],
    intent_primary: 'Explain state tracking',
  },
  {
    id: 'feature_state_007',
    name: 'State: Moment to Intervention',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'Your state check-in just triggered a NaviCue recommendation. That\'s the MAP at work.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Just-In-Time Support',
    theme_name: 'MAP Pipeline',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'state', 'demo', 'map', 'mindsteps'],
    intent_primary: 'Explain MAP pipeline',
  },
  {
    id: 'feature_state_008',
    name: 'State Integration: Decision OS',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Every state check-in feeds the Decision OS. The system learns what you need when.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Adaptive Intelligence',
    theme_name: 'System Learning',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'state', 'demo', 'decision_os', 'mindsteps'],
    intent_primary: 'Explain Decision OS integration',
  },
];

// Feature 4: Articles/Mind Steps (8 NaviCues)
const FEATURE_ARTICLES: NaviCue[] = [
  {
    id: 'feature_articles_001',
    name: 'Mind Step: The Window',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: Your window of tolerance is elastic. You can widen it with practice.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Window of Tolerance',
    theme_name: 'Neuroplasticity',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'mindsteps', 'articles', 'demo', 'insight'],
    intent_primary: 'Deliver window insight',
  },
  {
    id: 'feature_articles_002',
    name: 'Mind Step: The Gap',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: Between stimulus and response, there\'s a gap. That\'s where your power lives.',
    pillar_id: 'CR',
    pillar_name: 'Constructive Responsibility',
    pillar_color: '#F59E0B',
    concept_name: 'Response Flexibility',
    theme_name: 'The Gap',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'mindsteps', 'articles', 'demo', 'insight'],
    intent_primary: 'Deliver gap insight',
  },
  {
    id: 'feature_articles_003',
    name: 'Mind Step: Temporary States',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: States are temporary. Identity is durable. Know the difference.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'State vs Trait',
    theme_name: 'Distinction',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'mindsteps', 'articles', 'demo', 'insight'],
    intent_primary: 'Deliver state/trait insight',
  },
  {
    id: 'feature_articles_004',
    name: 'Mind Step: The Paradox',
    family: 'paradox_prompt',
    modality: 'text',
    text_line: 'Mind Step: The more you chase happiness, the more it eludes you. Peace is already here.',
    pillar_id: 'SC',
    pillar_name: 'Self Compassion',
    pillar_color: '#10B981',
    concept_name: 'Acceptance',
    theme_name: 'Paradox',
    response_type: 'paradox',
    kbe_target: 'believing',
    tags: ['feature', 'mindsteps', 'articles', 'demo', 'insight'],
    intent_primary: 'Deliver paradox insight',
  },
  {
    id: 'feature_articles_005',
    name: 'Mind Step: Connection as Medicine',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: Isolation is the petri dish of shame. Connection is the cure.',
    pillar_id: 'SC',
    pillar_name: 'Social Connection',
    pillar_color: '#10B981',
    concept_name: 'Relational Healing',
    theme_name: 'Connection Principle',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'mindsteps', 'articles', 'demo', 'insight'],
    intent_primary: 'Deliver connection insight',
  },
  {
    id: 'feature_articles_006',
    name: 'Article Format: Insight Delivery',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Articles break down complex ideas into bite-sized insights. This is one of them.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Learning Format',
    theme_name: 'Insight Delivery',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['feature', 'articles', 'demo', 'format'],
    intent_primary: 'Explain article format',
  },
  {
    id: 'feature_articles_007',
    name: 'Article: Layered Learning',
    family: 'identity_koan',
    modality: 'text',
    text_line: 'Mind Steps deliver in layers: Knowing → Believing → Embodying. Each layer deepens.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'KBE Framework',
    theme_name: 'Layered Learning',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'articles', 'mindsteps', 'demo', 'kbe'],
    intent_primary: 'Explain KBE progression',
  },
  {
    id: 'feature_articles_008',
    name: 'Article Integration: Schema Mapping',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Every Mind Step targets a specific schema. LUMA delivers insights when you need them most.',
    pillar_id: 'CR',
    pillar_name: 'Constructive Responsibility',
    pillar_color: '#F59E0B',
    concept_name: 'Schema Targeting',
    theme_name: 'Precision Delivery',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'articles', 'mindsteps', 'demo', 'luma'],
    intent_primary: 'Explain schema targeting',
  },
];

// Feature 5: Practices (8 NaviCues)
const FEATURE_PRACTICES: NaviCue[] = [
  {
    id: 'feature_practices_001',
    name: 'Practice: Box Breathing',
    family: 'practice',
    modality: 'audio',
    text_line: 'Breathe in for 4. Hold for 4. Out for 4. Hold for 4. Repeat.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Breath Regulation',
    theme_name: 'Box Breathing',
    response_type: 'breath',
    kbe_target: 'embodying',
    tags: ['feature', 'practices', 'demo', 'breathing', 'wellbeing'],
    intent_primary: 'Demo box breathing',
    duration_minutes: 2,
  },
  {
    id: 'feature_practices_002',
    name: 'Practice: 5-4-3-2-1 Grounding',
    family: 'practice',
    modality: 'text',
    text_line: 'Name 5 things you see. 4 you hear. 3 you feel. 2 you smell. 1 you taste.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Grounding',
    theme_name: '5-4-3-2-1',
    response_type: 'tap',
    kbe_target: 'embodying',
    tags: ['feature', 'practices', 'demo', 'grounding'],
    intent_primary: 'Demo 5-4-3-2-1 grounding',
  },
  {
    id: 'feature_practices_003',
    name: 'Practice: Body Scan',
    family: 'practice',
    modality: 'audio',
    text_line: 'Start at your feet. Notice any tension. Move up slowly. Just notice, don\'t fix.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Somatic Awareness',
    theme_name: 'Body Scan',
    response_type: 'body_map',
    kbe_target: 'embodying',
    tags: ['feature', 'practices', 'demo', 'somatic', 'wellbeing'],
    intent_primary: 'Demo body scan',
    duration_minutes: 3,
  },
  {
    id: 'feature_practices_004',
    name: 'Practice: Affirmation Echo',
    family: 'practice',
    modality: 'audio',
    text_line: 'Repeat after me: I am worthy. I am enough. I am growing.',
    pillar_id: 'SC',
    pillar_name: 'Self Compassion',
    pillar_color: '#10B981',
    concept_name: 'Self-Affirmation',
    theme_name: 'Affirmations',
    response_type: 'echo',
    kbe_target: 'embodying',
    tags: ['feature', 'practices', 'demo', 'affirmation'],
    intent_primary: 'Demo affirmation practice',
  },
  {
    id: 'feature_practices_005',
    name: 'Practice: Values Clarification',
    family: 'practice',
    modality: 'interactive',
    text_line: 'Sort these values by importance: Family, Career, Health, Connection, Growth, Peace.',
    pillar_id: 'DM',
    pillar_name: 'Developing Meaning',
    pillar_color: '#EC4899',
    concept_name: 'Values',
    theme_name: 'Values Sort',
    response_type: 'sort',
    kbe_target: 'knowing',
    tags: ['feature', 'practices', 'demo', 'values'],
    intent_primary: 'Demo values sort',
  },
  {
    id: 'feature_practices_006',
    name: 'Practice: Gratitude Reflection',
    family: 'practice',
    modality: 'text',
    text_line: 'Name three things you\'re grateful for today. Say them out loud.',
    pillar_id: 'SC',
    pillar_name: 'Self Compassion',
    pillar_color: '#10B981',
    concept_name: 'Gratitude',
    theme_name: 'Gratitude Practice',
    response_type: 'voice10',
    kbe_target: 'embodying',
    tags: ['feature', 'practices', 'demo', 'gratitude', 'voice'],
    intent_primary: 'Demo gratitude practice',
  },
  {
    id: 'feature_practices_007',
    name: 'Practice: Urge Surfing',
    family: 'practice',
    modality: 'audio',
    text_line: 'Notice the urge. Don\'t act on it. Ride it like a wave. It will pass.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Urge Management',
    theme_name: 'Urge Surfing',
    response_type: 'breath',
    kbe_target: 'embodying',
    tags: ['feature', 'practices', 'demo', 'urge_surfing', 'wellbeing'],
    intent_primary: 'Demo urge surfing',
    duration_minutes: 2,
  },
  {
    id: 'feature_practices_008',
    name: 'Practice Integration: Proof Chain',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Every practice you complete builds your proof chain. LUMA tracks your progress.',
    pillar_id: 'DM',
    pillar_name: 'Developing Meaning',
    pillar_color: '#EC4899',
    concept_name: 'Progress Tracking',
    theme_name: 'Proof System',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'practices', 'demo', 'proof', 'mindsteps'],
    intent_primary: 'Explain proof chain',
  },
];

// Feature 6: Wellbeing/Body (8 NaviCues)
const FEATURE_WELLBEING: NaviCue[] = [
  {
    id: 'feature_wellbeing_001',
    name: 'Wellbeing: Your Body Is Part of Recovery',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Recovery isn\'t just mental. Your body holds trauma. Movement releases it.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Somatic Healing',
    theme_name: 'Body-Mind Connection',
    response_type: 'tap',
    kbe_target: 'knowing',
    tags: ['feature', 'wellbeing', 'demo', 'somatic', 'mindsteps'],
    intent_primary: 'Introduce body-based healing',
  },
  {
    id: 'feature_wellbeing_002',
    name: 'Wellbeing: Gentle Movement',
    family: 'practice',
    modality: 'video',
    text_line: '5-minute gentle stretch. No pressure. Just movement.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Movement Practice',
    theme_name: 'Gentle Stretch',
    response_type: 'tap',
    kbe_target: 'embodying',
    tags: ['feature', 'wellbeing', 'demo', 'movement', 'video'],
    intent_primary: 'Demo wellbeing video',
    duration_minutes: 5,
  },
  {
    id: 'feature_wellbeing_003',
    name: 'Wellbeing: Sleep Hygiene',
    family: 'practice',
    modality: 'text',
    text_line: 'Your sleep affects your state. Rate your sleep quality from the last 7 days.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Sleep Quality',
    theme_name: 'Sleep Tracking',
    response_type: 'slider',
    kbe_target: 'knowing',
    tags: ['feature', 'wellbeing', 'demo', 'sleep', 'state'],
    intent_primary: 'Track sleep quality',
  },
  {
    id: 'feature_wellbeing_004',
    name: 'Wellbeing: Body Mapping',
    family: 'practice',
    modality: 'interactive',
    text_line: 'Where do you hold tension in your body? Tap the areas.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Somatic Awareness',
    theme_name: 'Tension Mapping',
    response_type: 'body_map',
    kbe_target: 'embodying',
    tags: ['feature', 'wellbeing', 'demo', 'somatic', 'body_map'],
    intent_primary: 'Demo body map response',
  },
  {
    id: 'feature_wellbeing_005',
    name: 'Wellbeing: Breath as Anchor',
    family: 'practice',
    modality: 'audio',
    text_line: 'Your breath is always available. Three deep breaths. That\'s all.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Breath Work',
    theme_name: 'Simple Breath',
    response_type: 'breath',
    kbe_target: 'embodying',
    tags: ['feature', 'wellbeing', 'demo', 'breathing'],
    intent_primary: 'Demo simple breath practice',
    duration_minutes: 1,
  },
  {
    id: 'feature_wellbeing_006',
    name: 'Wellbeing: Yoga for Recovery',
    family: 'practice',
    modality: 'video',
    text_line: '10-minute trauma-informed yoga. Move at your own pace.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Trauma-Informed Movement',
    theme_name: 'Yoga',
    response_type: 'tap',
    kbe_target: 'embodying',
    tags: ['feature', 'wellbeing', 'demo', 'yoga', 'video'],
    intent_primary: 'Demo yoga video',
    duration_minutes: 10,
  },
  {
    id: 'feature_wellbeing_007',
    name: 'Wellbeing: Nutrition Awareness',
    family: 'belief_probe',
    modality: 'text',
    text_line: 'How has your eating been? Nourished? Restricted? Chaotic? Just notice.',
    pillar_id: 'ER',
    pillar_name: 'Emotional Regulation',
    pillar_color: '#EF4444',
    concept_name: 'Self-Care',
    theme_name: 'Nutrition',
    response_type: 'one_word',
    kbe_target: 'knowing',
    tags: ['feature', 'wellbeing', 'demo', 'nutrition'],
    intent_primary: 'Check nutrition awareness',
  },
  {
    id: 'feature_wellbeing_008',
    name: 'Wellbeing Integration: Holistic Recovery',
    family: 'statement_mirror',
    modality: 'text',
    text_line: 'Mind Step: Recovery is holistic. Mind, body, spirit — all interconnected.',
    pillar_id: 'II',
    pillar_name: 'Identity Integration',
    pillar_color: '#8B5CF6',
    concept_name: 'Holistic Healing',
    theme_name: 'Integration',
    response_type: 'tap',
    kbe_target: 'believing',
    tags: ['feature', 'wellbeing', 'demo', 'mindsteps', 'holistic'],
    intent_primary: 'Explain holistic approach',
  },
];

// ============================================================================
// EXPORT COMBINED BATCH
// ============================================================================

export const JOURNEY_NAVICUES = [
  ...JOURNEY_SPRINT_1,
  ...JOURNEY_SPRINT_2,
  ...JOURNEY_SPRINT_3,
  ...JOURNEY_SPRINT_4,
];

export const FEATURE_INTEGRATION_NAVICUES = [
  ...FEATURE_VOICE,
  ...FEATURE_STORY,
  ...FEATURE_STATE,
  ...FEATURE_ARTICLES,
  ...FEATURE_PRACTICES,
  ...FEATURE_WELLBEING,
];

export const NAVICUE_BATCH_JOURNEY_FEATURES = [
  ...JOURNEY_NAVICUES,
  ...FEATURE_INTEGRATION_NAVICUES,
];

// Stats
export const BATCH_STATS = {
  total: NAVICUE_BATCH_JOURNEY_FEATURES.length,
  journey: JOURNEY_NAVICUES.length,
  journey_sprint_1: JOURNEY_SPRINT_1.length,
  journey_sprint_2: JOURNEY_SPRINT_2.length,
  journey_sprint_3: JOURNEY_SPRINT_3.length,
  journey_sprint_4: JOURNEY_SPRINT_4.length,
  feature_integration: FEATURE_INTEGRATION_NAVICUES.length,
  feature_voice: FEATURE_VOICE.length,
  feature_story: FEATURE_STORY.length,
  feature_state: FEATURE_STATE.length,
  feature_articles: FEATURE_ARTICLES.length,
  feature_practices: FEATURE_PRACTICES.length,
  feature_wellbeing: FEATURE_WELLBEING.length,
};
