/**
 * TRANSFORMATION TEMPLATES
 * Poetic, neuroscientific, spiritual copy for all NaviCue families
 */

export const CURVEBALL_TEMPLATES = {
  shame: [
    'Take up space today. Big, unapologetic, visible space. Notice what happens.',
    'Ask for something you want without justifying why you deserve it.',
    'Accept one compliment today without deflecting, minimizing, or explaining it away.',
    'Share something imperfect. A messy thought. A half-formed idea. See who stays.',
  ],
  control: [
    'Let someone else decide today. Dinner, the route, the plan. Surrender the wheel.',
    'Leave one thing undone. On purpose. Watch what happens when you stop managing.',
    `Say "I don't know" three times today. Notice if the world actually ends.`,
    'Ask for help with something small. Before you actually need it. Practice receiving.',
  ],
  abandonment: [
    `Reach out first. Text someone. Don't wait to be chosen. Be the one who chooses.`,
    `Tell someone you miss them. Before they say it first. Risk being the one who cares more.`,
    'Share a fear with someone safe. Not a fact. A fear. See if they can hold it.',
    'Stay five minutes longer in connection even when your body says to leave.',
  ],
  perfectionism: [
    `Submit something before it's perfect. Hit send. Post it. Turn it in. Breathe.`,
    'Make one mistake on purpose today. Misspell something. Leave a typo. Survive it.',
    'Do something poorly. Cook badly. Draw badly. Dance badly. Be gloriously mediocre.',
    'Set a timer for 10 minutes. Do the thing. Stop when the timer ends. Done is enough.',
  ],
  victimhood: [
    'Make one decision today without asking for input. Own it. See what changes.',
    'Say no to something you usually tolerate. Reclaim your boundary. Feel your power.',
    `Take credit for something good today. Don't deflect. Don't minimize. Own it.`,
    'Change one small thing in your environment. Move a chair. Rearrange. You have agency.',
  ],
  'emotional-suppression': [
    `Feel one feeling fully for 90 seconds. Set a timer. Don't suppress. Don't perform. Just feel.`,
    `Say out loud: "I feel [emotion]." Don't explain it. Don't justify it. Just name it.`,
    `Cry if tears come. Don't stop them. Let your body release what it's been holding.`,
    'Tell someone how you really feel. Not fine. Not okay. The actual truth.',
  ],
  'people-pleasing': [
    `Say no to one request today. Don't explain. Don't justify. Just no.`,
    'Disappoint someone small. Skip the optional thing. Notice you both survive.',
    'Share an opinion someone might disagree with. See if the relationship can hold it.',
    'Do something you want instead of what they need. Choose yourself. Watch what happens.',
  ],
  scarcity: [
    'Give something away today. Money, time, food. Practice abundance.',
    'Buy the thing without waiting for a sale. Spend without scarcity. You have enough.',
    'Share your resources. Your time. Your knowledge. Your food. Notice the well refills.',
    `Throw away something you're hoarding. Old receipts. Expired coupons. Let go.`,
  ],
  comparison: [
    `Celebrate someone else's win today. Genuinely. Without making it about you.`,
    'Delete one social media app for 24 hours. Stop comparing. Be here. Be you.',
    'Say one thing you love about yourself. Out loud. To someone. Own your worth.',
    'Unfollow one account that makes you feel less than. Protect your peace.',
  ],
  catastrophizing: [
    `Ask yourself: "What if it works out?" Sit with that possibility for 60 seconds.`,
    'Notice one thing going right today. Write it down. Evidence against the disaster.',
    `When the spiral starts, place your hand on your heart. Ask: "Am I safe right now?"`,
    'Plan for the best case scenario. Write it out. Give hope the same energy as fear.',
  ],
  'identity-fusion': [
    'Introduce yourself without your job, role, or story. Who are you beneath the labels?',
    'Do something completely unrelated to your identity. Be a beginner. Be nameless.',
    'Sit in silence for 5 minutes. No doing. No achieving. Just being. Who remains?',
    `Complete this sentence: "I am more than my [identity]." Say it three times.`,
  ],
  'safety-seeking': [
    'Do one small uncomfortable thing today. Order something new. Take a different route.',
    'Say yes to an invitation that scares you a little. Growth lives in the discomfort.',
    `Share an idea before it's fully formed. Risk looking foolish. Be brave.`,
    `Try something you might fail at. Start anyway. Failure won't kill you. Regret might.`,
  ],
};

export const PRACTICE_TEMPLATES = {
  shame: [
    `Place your hand on your heart. Say aloud: "I am enough exactly as I am." Repeat until you can breathe.`,
    `Write down one thing you're proud of. Not for what it achieved, but for what it revealed about you.`,
    `Mirror practice: Look yourself in the eyes for 60 seconds. Stay. Don't look away. You're safe here.`,
    `Name three things your body allows you to do today. Thank it. Even if it's imperfect.`,
  ],
  control: [
    'Box breathing: 4 counts in, 4 hold, 4 out, 4 hold. Release control with each exhale.',
    'Write down what you can control vs what you cannot. Release the second list. Burn it if you need to.',
    `Body scan: Start at your toes. Notice where you're gripping. Soften. Let go. Muscle by muscle.`,
    'Practice uncertainty: Choose something small. Flip a coin. Let chance decide. Survive not knowing.',
  ],
  abandonment: [
    'Self-soothing practice: When abandonment panic hits, place both hands on your chest. You are here.',
    'Write a letter to younger you. The one who was left. Tell them they are never alone again.',
    `Connection practice: Text three people. No agenda. Just: "Thinking of you." Risk being seen.`,
    `Sit with loneliness for 5 minutes. Don't fix it. Don't run. Just be with it. It won't kill you.`,
  ],
  perfectionism: [
    `Done > perfect practice: Set a timer for 15 minutes. Work. Stop when it rings. Submit it. Breathe.`,
    `Mistake log: Write down every mistake today. At the end, notice: You're still here. Still whole.`,
    `B-minus practice: Intentionally do something at 80%. Notice the world doesn't end.`,
    `Compassion meditation: Place hand on heart. Say: "It's okay to be imperfect. I'm still worthy."`,
  ],
  victimhood: [
    'Agency practice: Make three decisions today without asking permission. Own your power.',
    `Gratitude + responsibility: Write what you're grateful for AND what you're creating. Both matter.`,
    'Boundary practice: Say no to one thing you usually tolerate. Notice your power return.',
    `Identity shift: Replace "This happened to me" with "I experienced this." Feel the difference.`,
  ],
  'emotional-suppression': [
    'Emotion mapping: Draw your body. Color where you feel each emotion. Make the invisible visible.',
    'Feeling practice: Set a timer. Feel one emotion fully for 90 seconds. It will pass. You will survive.',
    `Voice it: Say aloud "I feel [emotion] and that's okay." Name it. Normalize it. Release it.`,
    `Release ritual: Cry, scream, move. Let your body discharge what it's been holding.`,
  ],
  'people-pleasing': [
    'No practice: Say no to one small request today. Notice the relationship survives.',
    'Needs assessment: Write down what YOU need today. Not them. You. Honor one need.',
    `Boundary script: "I can't do that, but I can do this." Practice the middle ground.`,
    `Resentment audit: Where do you feel resentment? That's where you need a boundary.`,
  ],
  scarcity: [
    'Abundance meditation: Close your eyes. Notice everything you have right now. Breathe it in.',
    'Generosity practice: Give something away. Time, money, food. Practice overflow.',
    'Enough inventory: List 10 things you have enough of. Read it when scarcity whispers.',
    `Gratitude ritual: Every morning, name three things you're grateful to have. Train the lens.`,
  ],
  comparison: [
    'Stay in your lane practice: When you start comparing, come back to your breath. Your body. Your path.',
    `Celebration practice: Genuinely celebrate someone else's win. Feel your heart open instead of contract.`,
    'Unique inventory: List 5 things only you can offer. Own your irreplaceable self.',
    'Social media detox: 24 hours offline. Notice how much quieter the comparison voice gets.',
  ],
  catastrophizing: [
    `Reality check: When the spiral starts, ask: "Is this happening right now?" Ground in the present.`,
    'Best case scenario: Write out what happens if everything goes RIGHT. Balance the narrative.',
    `Worry window: Set a timer for 10 minutes. Worry fully. When it rings, stop. You're done.`,
    `Evidence log: Write down past fears that didn't happen. Your brain needs proof it's wrong.`,
  ],
  'identity-fusion': [
    `Witness practice: Sit in silence. Notice thoughts. Notice you're the one noticing. Feel the space.`,
    `Label check: Every time you say "I am [identity]," add: "...and I am more than that."`,
    'Beginner practice: Do something totally unrelated to your identity. Be anonymous. Be no one.',
    `Morning question: Before roles activate, ask: "Who am I before I am anything?" Sit with it.`,
  ],
  'safety-seeking': [
    'Comfort zone stretch: Do one thing outside your routine. New coffee shop. Different route. Expand.',
    'Risk tolerance practice: Take one small risk today. Share an opinion. Try something new. Survive.',
    'Uncertainty practice: Make one decision without researching. Trust your gut. See what happens.',
    'Brave body practice: Notice where fear lives in your body. Breathe into it. Soften around it.',
  ],
};

// ============================================================================
// IDENTITY KOANS (301-400)
// Consciousness-pointing questions that dissolve identification
// ============================================================================

export const KOAN_TEMPLATES = {
  shame: [
    'The pond reflects everything without judgment. Mountains, garbage, moonlight. What if your awareness works the same way?',
    'Shame says: I am the stain. Presence asks: who is watching shame arise?',
    'Before the story of unworthiness, before the evidence of flaw, what remains?',
    'The sky never apologizes for storms. What in you existed before you learned to be sorry?',
    'Shame is a costume. The question is not how to fix it. The question is: who wore it first?',
    'When shame dissolves, even for a breath, what is the shape of the space it leaves?',
    'If unworthiness is a spell someone cast, what language breaks it? And who remembers that language?',
    'The river carries mud without becoming mud. What in you knows this same flowing?',
  ],
  control: [
    'The tree does not control the wind. Yet it dances. What knows how to move without managing?',
    'Control is a fist around water. What remains when the hand finally opens?',
    'Before the need to predict, before the plan, before the grip, what breathes?',
    'The ocean has no CEO. Tides turn without permission. What rhythm runs through you the same way?',
    'Chaos terrifies because it reveals: something moves that you did not authorize. Who is the you that notices?',
    'When everything falls apart, what remains that cannot fall?',
    'The question is not: how do I control this? The question is: who fears the uncontrollable?',
    'Certainty is the costume. Underneath, what vast not-knowing holds everything in place?',
  ],
  abandonment: [
    'Before the leaving, before the staying, before the fear of both, what breathes?',
    'Abandonment says: everyone leaves. Presence asks: what remains that cannot be left?',
    'The moon waxes and wanes. The ocean does not call this abandonment. What in you knows this rhythm?',
    'When everyone leaves, something stays. Not hope. Not faith. What is it?',
    'Connection breaks. Bonds dissolve. Yet awareness remains unbroken. What knows this?',
    'Alone is not the same as abandoned. The question is: who distinguishes them?',
    'Before you learned that closeness means pain, what did you know about love?',
    'The space between people is not absence. What fills it when fear is not filling it?',
  ],
  perfectionism: [
    'Perfection is a horizon. The question is not: how do I reach it? The question is: who is walking?',
    'Before the standard, before the ideal, before the measure, what moves?',
    'The mountain does not ask if it is perfect. What in you existed before evaluation?',
    'Flawlessness is a cage made of mirrors. When you stop checking your reflection, what emerges?',
    'Every mistake is proof you are more than the image. What perceives this?',
    'Good enough terrifies because it reveals: the ground holds you anyway. Who stands on that ground?',
    'Excellence is a costume. Underneath, what works without needing applause?',
    'The crack is not failure. The crack is where light enters. Who sees the light?',
  ],
  victimhood: [
    'The wave says: the ocean does this to me. What knows the wave IS the ocean?',
    'Powerlessness is real. The question is not: am I powerful? The question is: who asks?',
    'Before the story of what happened, before the identity of the one it happened to, what breathes?',
    'Things happen. The question is not: why me? The question is: who witnesses the happening?',
    'Victimhood says: I had no choice. Presence asks: who is choosing right now?',
    'The seed does not blame the ground for growing. What in you moves without permission?',
    'Agency is not control. Agency is response. What in you is always responding?',
    'When nothing changes, something still chooses how to meet it. Who is that?',
  ],
  'emotional-suppression': [
    'Feelings arise like weather. The question is not: how do I stop the storm? The question is: what is the sky?',
    'Before the strategy of hiding, before the fear of feeling, what feels?',
    'Suppression protects by numbing. The question is: what remains that does not need protection?',
    'Emotion is motion. When you stop the movement, what stagnates? When you allow it, what flows?',
    'Before you learned that feelings are dangerous, what did you know about aliveness?',
    'The body holds what the mind refuses. The question is: who refuses? Who holds?',
    'When suppression finally fails, the flood comes. But what remains after the flood?',
    'Feelings pass like clouds. The issue is not the cloud. The issue is mistaking yourself for the cloud.',
  ],
  'people-pleasing': [
    'The mirror reflects everyone but has no preferences. What in you existed before you learned to adjust?',
    'Pleasing is a strategy. The question is not: how do I stop? The question is: who strategizes?',
    'Before the need to be liked, before the fear of rejection, what loves?',
    'The river does not ask permission to flow. What current runs through you the same way?',
    'When you disappoint someone and survive, what becomes possible?',
    'People-pleasing says: I am what they need me to be. Presence asks: who is the I underneath the adaptation?',
    'Approval is a drug. Withdrawal is painful. But what remains when the craving quiets?',
    'No is a complete sentence. The question is: who speaks it? And who fears speaking it?',
  ],
  scarcity: [
    'The well fears running dry. The ocean never does. What is the difference? And where do you live?',
    'Scarcity says: there is never enough. Presence asks: enough for what? And who measures?',
    'Before the counting, before the hoarding, before the fear, what is already here?',
    'Abundance is not more. Abundance is the end of measuring. What stops measuring?',
    'The body breathes without asking if there is enough air. What else operates this way?',
    'When you finally have enough, will it be enough? Or will the target move again?',
    'Scarcity is a lens. When the lens is removed, what does the eye see?',
    'Before the lack, before the not-enough, what fullness existed that you cannot remember?',
  ],
  comparison: [
    'The oak does not envy the willow. What in you existed before you learned to measure against others?',
    'Comparison says: I am less than. Presence asks: less than what? And who is comparing?',
    'Before the contest, before the ranking, before the better/worse, what moves?',
    'When you are alone in the forest, does your worth change? If not, what does that reveal?',
    'Better is a direction with no destination. The question is not: how do I get there? The question is: who is walking?',
    'Social media is a hall of mirrors. Each reflection is distorted. What sees clearly?',
    'The moon does not compete with the sun. Different light. Different time. What in you knows this?',
    'When comparison dissolves, even for a moment, what remains? And is it less? Or more? Or neither?',
  ],
  catastrophizing: [
    'The mind rehearses disaster to prepare. The question is not: how do I stop? The question is: who rehearses? Who watches?',
    'Before the worst-case scenario, before the spiral, before the fear, what is actually happening right now?',
    'Catastrophizing is a spell. The incantation is: what if. The counter-spell is: what is. Who speaks which?',
    'The future is not real. The disaster is not here. Yet fear is real. Who feels it? And where?',
    'When the catastrophe finally arrives, something meets it. Not fear. Not preparation. What is it?',
    'Worst case: everything falls apart. The question is not: how do I prevent this? The question is: what remains that cannot fall apart?',
    'The mind time-travels to disaster. The body stays here. Which one is wiser?',
    'Before the spiral, there is one breath. Just one. What chooses to take it?',
  ],
  'identity-fusion': [
    'The actor plays the role. The role is not the actor. What in you plays all the roles?',
    'Identity says: I am this. Presence asks: who is aware of this?',
    'Before the name, before the story, before the resume, what breathes?',
    'The costume is not the person. Yet we forget. What remembers?',
    'When you are not your job, your trauma, your achievements, what remains? And is it nothing? Or everything?',
    'Fusion is forgetting the space between observer and observed. What space? Look now.',
    'The wave thinks it is only a wave. Until it remembers: I am also the ocean. What remembers?',
    'Who are you when no one is looking? Not performing, not producing, not proving. Who remains?',
  ],
  'safety-seeking': [
    'Safety is the fence. Freedom is beyond it. The question is not: which side? The question is: who chooses?',
    'Before the need for certainty, before the strategy of control, what trusts?',
    'The bird leaves the nest not because it is safe, but because it is time. What in you knows this timing?',
    'Comfort is a castle. Growth is the wilderness. Where do you live? And who decides?',
    'Safety-seeking says: I cannot risk this. Presence asks: who is the I that would be risked?',
    'Every wall built for protection also blocks the view. What sees beyond the wall?',
    'The seed breaks open in the dark. This is not safe. This is necessary. What in you knows the difference?',
    'When you finally feel safe, will you live? Or will you need more safety first?',
  ],
};

// ============================================================================
// PARADOX PROMPTS (401-500)
// AND statements that hold both truths simultaneously
// ============================================================================

export const PARADOX_TEMPLATES = {
  shame: [
    'Shame lives in the body. AND the body is not the shame.',
    'The story of unworthiness is real. AND the one who hears the story is untouched by it.',
    'Feeling flawed does not make you flawed. Both can be true: the feeling AND the wholeness underneath.',
    'Shame says: hide. Healing says: be seen. The paradox: both impulses can coexist until one becomes louder.',
    'You can carry shame AND still be worthy. One does not cancel the other. This is the work.',
    'The voice of not-enough is loud. AND it is not the only voice. Both exist. Which one feeds the future?',
    'Shame is real evidence of a real wound. AND it is not real evidence of actual deficiency.',
    'You can feel fundamentally broken AND be fundamentally whole. The brokenness is the feeling. The wholeness is what feels it.',
  ],
  control: [
    'Control is impossible. AND letting go is terrifying. Both truths can live in the same breath.',
    'You can release the grip AND still feel the fear of falling. Freedom does not require fearlessness.',
    'The future is uncertain. AND uncertainty is not the same as danger. Both can be true at once.',
    'You can surrender control AND still take action. Letting go is not the same as giving up.',
    'Chaos is real. AND the one who witnesses chaos is not chaotic. Both exist simultaneously.',
    'Planning helps. AND over-planning suffocates. The line between them is breath.',
    'You can admit you don\'t know AND still move forward. Not-knowing is not the same as incapable.',
    'Control protects. AND control exhausts. Both are true. The question is: which truth serves you now?',
  ],
  abandonment: [
    'People leave. AND their leaving does not define your worth. Both hurt. Only one is true.',
    'Closeness is risky. AND isolation is not safer. Both are painful. Which pain grows you?',
    'You can fear abandonment AND still choose connection. The fear does not have to be the boss.',
    'Alone is real. AND aloneness is not the same as unlovable. Both can exist without merging.',
    'The past taught you that leaving is inevitable. AND the present is not the past. Both are true.',
    'You can be terrified of loss AND still love deeply. Courage is not the absence of fear.',
    'Everyone you love will leave or die or change. AND love is still worth it. This is the human deal.',
    'Abandonment is a wound. AND wounds can heal while still being tender. Both are part of the path.',
  ],
  perfectionism: [
    'Excellence matters. AND perfection is a cage. Both can be true without contradiction.',
    'You can do your best AND your best can be imperfect. These are not opposites.',
    'High standards serve growth. AND impossible standards serve nothing but fear.',
    'Mistakes are proof of trying. AND trying is proof of aliveness. Perfection is proof of neither.',
    'You can care deeply about your work AND release the outcome. Both are possible. This is mastery.',
    'Good enough is sometimes excellent. AND excellent is sometimes not enough. Context decides. Not fear.',
    'Perfectionism protects you from judgment. AND it also prevents you from living. Both are true. Choose.',
    'You can strive AND rest. Both are necessary. Perfection only demands one. Wholeness requires both.',
  ],
  victimhood: [
    'Things happened to you. AND you are not only what happened. Both are true. One is larger.',
    'Powerlessness is real. AND response is always possible. Both can exist in the same moment.',
    'You did not choose the wound. AND you choose what happens next. Both matter. One moves you forward.',
    'The past shaped you. AND the past does not own you. Both are accurate. Which one runs the show?',
    'You can be impacted by circumstances AND still have agency. Victimhood and empowerment are not opposites.',
    'Life is unfair. AND unfairness is not the whole story. Both are real. Which story builds the future?',
    'You can honor the pain AND claim your power. Healing is not choosing one or the other.',
    'What happened was not your fault. AND what happens next is your responsibility. Both are true. This is freedom.',
  ],
  'emotional-suppression': [
    'Feelings are overwhelming. AND they are also temporary. Both are true. The wave always passes.',
    'You can feel everything AND still function. Emotion and capability are not enemies.',
    'Suppression kept you safe once. AND now it keeps you small. Both were necessary. Only one still is.',
    'You can be afraid of your feelings AND still feel them. Fear does not have to be the gatekeeper.',
    'Emotions are intense. AND intensity is not the same as danger. Both can be true without disaster.',
    'The body holds what the mind cannot process. AND processing is possible now. Both matter. One heals.',
    'You can honor the strategy of numbing AND choose something else now. Gratitude and growth coexist.',
    'Feelings will not kill you. AND the fear of them is real. Both truths can breathe in the same room.',
  ],
  'people-pleasing': [
    'You can care about others AND prioritize yourself. Both are possible. Neither is selfish.',
    'Saying no will disappoint someone. AND their disappointment will not destroy you. Both are survivable.',
    'Connection matters. AND connection built on self-abandonment is not real connection. Both are true.',
    'You can be kind AND have boundaries. These are not opposites. They are partners.',
    'People-pleasing keeps you safe. AND it also keeps you hidden. Both are true. Which serves your future?',
    'You can want to be liked AND still speak your truth. Approval and authenticity can coexist.',
    'Disappointing others is uncomfortable. AND disowning yourself is unbearable. Both hurt. One grows you.',
    'You can honor their needs AND honor your own. Both matter. When only one does, resentment grows.',
  ],
  scarcity: [
    'Resources are finite. AND scarcity is a mindset, not just a fact. Both are true. One you can shift.',
    'You can save for the future AND enjoy the present. Both are wise. Fear only sees one.',
    'Not having enough is real. AND the fear of not-enough often exceeds the reality. Both exist. Check which is louder.',
    'You can be careful with resources AND still practice generosity. Scarcity and abundance are choices, not just circumstances.',
    'There will never be enough to silence the scarcity voice. AND you can stop listening anyway. Both are true.',
    'Money matters. AND money is not the only measure of wealth. Both are accurate. Which lens do you use?',
    'You can honor the lack AND refuse to be defined by it. Both are possible. One is liberation.',
    'Scarcity was real in your past. AND your present is not your past. Both are true. Which timeline are you living?',
  ],
  comparison: [
    'Someone will always be ahead. AND your path is not their path. Both are true. Only one is yours.',
    'You can admire others AND honor yourself. Both are possible without diminishment.',
    'Comparison is natural. AND natural does not mean useful. Both are true. Choose which to follow.',
    'You can see their success AND celebrate your own. Both exist. Scarcity says only one can matter.',
    'Social media distorts reality. AND your response to it is yours to shape. Both are true. One is actionable.',
    'You can want what they have AND still love what you have. Both are human. One brings peace.',
    'Your worth does not decrease when someone else succeeds. Both of you can be whole. This is not a competition.',
    'Comparison highlights gaps. AND gaps are where growth lives. Both are true. One is painful. One is possibility.',
  ],
  catastrophizing: [
    'The worst could happen. AND it probably won\'t. Both are true. Which one gets your energy?',
    'Preparing for disaster is wise. AND living in disaster before it arrives is torture. Both are true. Find the line.',
    'You can acknowledge the risk AND trust the resilience. Both are real. Fear only sees one.',
    'Catastrophizing is a strategy for control. AND it doesn\'t actually prevent catastrophe. Both are true. One is exhausting.',
    'The future is uncertain. AND uncertainty is not the same as doom. Both can coexist without panic.',
    'Bad things happen. AND most of what you fear never arrives. Both are facts. Which one runs your life?',
    'You can plan for the worst AND hope for the best. Both are possible. Balance is the work.',
    'The spiral is real. AND you can interrupt it. Both are true. One requires practice. Both are worth it.',
  ],
  'identity-fusion': [
    'You are shaped by your story. AND you are not only your story. Both are true. One is freedom.',
    'Your roles matter. AND you are more than your roles. Both can exist without conflict.',
    'Identity provides structure. AND it also limits possibility. Both are true. Which serves you now?',
    'You can honor what you do AND remember you are not what you do. Both matter. One is primary.',
    'The labels describe you. AND they do not define you. Both are accurate. Which one breathes?',
    'You are the actor AND the role. Both are true. Fusion is forgetting the difference.',
    'Your achievements are real. AND your worth is not contingent on them. Both are true. One is liberation.',
    'You can be known for something AND still be mystery underneath. Both are true. One is infinite.',
  ],
  'safety-seeking': [
    'Safety matters. AND too much safety is a cage. Both are true. The line shifts with each breath.',
    'You can honor the fear AND take the risk. Both are possible. Courage is not the absence of fear.',
    'Certainty is comforting. AND growth requires uncertainty. Both are true. Choose which god to serve.',
    'You can protect yourself AND open to life. Both are necessary. Safety-seeking only sees one.',
    'Staying safe prevents pain. AND it also prevents aliveness. Both are true. Which cost can you bear?',
    'Risk is real. AND so is regret. Both hurt. Which hurt moves you forward?',
    'You can plan for safety AND surrender to the unknown. Both are wisdom. Fear only permits one.',
    'The comfort zone is real. AND everything you want is outside it. Both are true. The choice is daily.',
  ],
};

// ============================================================================
// STORY MAPPING (501-620)
// Excavation invitations that name the origin moment
// ============================================================================

export const STORY_MAP_TEMPLATES = {
  shame: [
    'There was a day shame first entered. A moment when unworthiness became the lens. What was the weather that day?',
    'Someone said something. Or did something. Or failed to do something. And the verdict landed: not enough. When was that?',
    'Before shame, there was innocence. Then came the moment. The event. The shattering. What broke?',
    'The first time hiding felt safer than being seen. The first time smallness felt like survival. When did that become the strategy?',
    'Unworthiness is learned, not inherent. Someone taught it. Some moment installed it. What was the installation ceremony?',
    'There is a scene where shame planted its flag. A memory where the voice first whispered: you are too much, or not enough. What is that scene?',
    'The body remembers the moment before shame and the moment after. Between them, something changed. What changed?',
    'Shame became the default setting. But once, it was not. Once, there was a different operating system. What happened to it?',
  ],
  control: [
    'There was a moment chaos arrived and control became the strategy. When did gripping replace trusting?',
    'Something felt out of control once. Something big. Something terrifying. And hypervigilance became the answer. What was the question?',
    'Before control, there was surrender. Before the need to manage, there was flow. What moment ended that?',
    'The first time unpredictability felt like danger. The first time letting go felt like falling. When was that?',
    'Control is a response to powerlessness. Somewhere, once, power was taken. When did taking it back become the mission?',
    'There is a memory where uncertainty stopped feeling like adventure and started feeling like threat. What shifted?',
    'Hypervigilance is exhausting. And yet it persists. Because once, it saved you. From what? And when?',
    'The grip tightened around something specific. Some event. Some betrayal. Some collapse. What was it?',
  ],
  abandonment: [
    'There was a leaving. A first leaving. The one that taught the pattern: closeness equals loss. When was that?',
    'Someone was supposed to stay and did not. The absence carved a belief: people leave. Who left first?',
    'Before abandonment, there was trust. Before distance, there was closeness. What moment severed them?',
    'The first time reaching out resulted in emptiness. The first time connection resulted in pain. When did that become the expectation?',
    'Abandonment is not just departure. It is the moment you decided: I am not worth staying for. When did you decide that?',
    'There is a scene where aloneness became identity. Where isolation became safety. What scene?',
    'Someone left. And the story you told yourself about why became the core belief. What story? Whose voice?',
    'The fear of abandonment is not about the future. It is about the past on repeat. What past? What repeat?',
  ],
  perfectionism: [
    'There was a moment good enough stopped being enough. When did excellence become the entry fee for worth?',
    'Someone set a standard. Or withheld love until the standard was met. Who was that? What was the standard?',
    'Before perfectionism, there was playfulness. Before striving, there was ease. What moment killed ease?',
    'The first time a mistake resulted in shame, rejection, or punishment. The first time flawlessness felt like survival. When?',
    'Perfectionism is not about excellence. It is about fear. Fear of what? Installed when?',
    'There is a memory where imperfection became intolerable. Where the bar raised and never lowered. What raised it?',
    'Someone needed you to be perfect. Or you believed they did. The pressure landed. When did it land?',
    'Before the chase for flawlessness, there was permission to be human. What moment revoked the permission?',
  ],
  victimhood: [
    'There was an event where power was taken. Where agency dissolved. Where victimhood became identity. What event?',
    'Something happened TO you. And the story became: things happen TO me. When did the story solidify?',
    'Before victimhood, there was empowerment. Before helplessness, there was choice. What moment collapsed choice?',
    'The first time powerlessness felt total. The first time nothing you did mattered. When was that?',
    'Victimhood is not the event. It is the interpretation of the event. What interpretation? Whose voice delivered it?',
    'There is a scene where giving up felt safer than trying. Where surrender became identity. What scene?',
    'Someone convinced you that you are powerless. Or circumstances did. When did the conviction take root?',
    'The narrative of no-choice began somewhere. With someone. In some situation. Where?',
  ],
  'emotional-suppression': [
    'There was a feeling too big to feel. And suppression became the strategy. What feeling? What made it too big?',
    'Someone said feelings are dangerous, weak, too much, not allowed. Who said that? When did you believe them?',
    'Before suppression, there was expression. Before numbing, there was feeling. What moment built the wall?',
    'The first time a feeling resulted in punishment, rejection, or danger. The first time hiding felt safer. When?',
    'Emotional suppression is protection. But protection from what? From whom? Installed when?',
    'There is a memory where feelings stopped being safe. Where expression stopped being allowed. What memory?',
    'Someone could not hold your emotion. Or shamed you for having it. Who could not hold you?',
    'Before the shutdown, there was aliveness. Before the numbing, there was intensity. What moment dimmed the light?',
  ],
  'people-pleasing': [
    'There was a moment your needs stopped mattering. When did making others happy become your job?',
    'Someone needed you to be easy, compliant, accommodating. Who needed that? And what happened when you were not?',
    'Before people-pleasing, there were boundaries. Before self-abandonment, there was self. What moment erased self?',
    'The first time saying no resulted in rejection, anger, or withdrawal. The first time yes felt like survival. When?',
    'People-pleasing is a strategy. But a strategy for what? Safety? Love? Belonging? From whom? Since when?',
    'There is a scene where disappointing someone felt like annihilation. Where their needs eclipsed yours. What scene?',
    'Someone taught you that your worth depends on their approval. Who was the teacher? What was the lesson?',
    'Before the performance, there was authenticity. Before the adjustment, there was truth. What moment silenced truth?',
  ],
  scarcity: [
    'There was a moment not-enough became the operating system. When did scarcity become the lens?',
    'Something was scarce once. Food, money, love, safety. And the scarcity carved a belief: there will never be enough. What was scarce?',
    'Before scarcity, there was abundance. Or at least ease. What moment ended ease?',
    'The first time you went without. The first time lack felt like identity. When was that?',
    'Scarcity is not just circumstance. It is belief. The belief began somewhere. With someone. In some situation. Where?',
    'There is a memory where having enough stopped feeling possible. Where the well ran dry. What dried the well?',
    'Someone hoarded, worried, rationed, feared. And you learned the pattern. Who was that? What did they fear?',
    'Before the scarcity mindset, there was trust. Trust that enough exists. What moment broke the trust?',
  ],
  comparison: [
    'There was a moment being yourself stopped being enough. When did measuring against others become the metric?',
    'Someone compared you to someone else. And the comparison carved a belief: I am less than. Who did the comparing?',
    'Before comparison, there was self-acceptance. Before ranking, there was belonging. What moment introduced the hierarchy?',
    'The first time someone else\'s success felt like your failure. The first time their worth diminished yours. When?',
    'Comparison is learned. Someone taught it. Some system reinforced it. What was the first lesson?',
    'There is a scene where uniqueness became inadequacy. Where your path became wrong because it was not their path. What scene?',
    'Someone held you up to a standard that was not yours. And you internalized it. Who set the standard? What was it?',
    'Before the race, there was your own pace. Before the contest, there was your own journey. What moment started the race?',
  ],
  catastrophizing: [
    'There was a moment the worst happened. And the belief formed: the worst will always happen. What was the worst?',
    'Something bad arrived without warning. And vigilance became the strategy. What arrived? When did hypervigilance become default?',
    'Before catastrophizing, there was trust. Trust that things would be okay. What moment shattered trust?',
    'The first time preparation failed and disaster struck. The first time safety was an illusion. When was that?',
    'Catastrophizing is not paranoia. It is pattern recognition. What pattern? From when?',
    'There is a memory where the future became a threat. Where hope became dangerous. What memory?',
    'Someone taught you to expect the worst. By example, by experience, by repetition. Who was the teacher?',
    'Before the spiral, there was possibility. Before disaster-thinking, there was openness. What moment closed the future?',
  ],
  'identity-fusion': [
    'There was a moment you became your role, your story, your achievement, your trauma. When did fusion replace fluidity?',
    'Someone told you: you ARE this. Not: you experienced this. Not: you do this. You ARE this. Who said that?',
    'Before fusion, there was space between self and role. What moment collapsed the space?',
    'The first time your identity became your worth. The first time the label became the self. When?',
    'Identity fusion is not clarity. It is collapse. What collapsed? And when?',
    'There is a scene where forgetting yourself felt necessary. Where becoming the role felt like survival. What scene?',
    'Someone needed you to be a thing, not a person. A function, not a self. Who needed that?',
    'Before the costume became the self, there was distinction. What moment erased distinction?',
  ],
  'safety-seeking': [
    'There was a moment risk stopped feeling like adventure and started feeling like danger. When did safety become the primary goal?',
    'Something unsafe happened. And the belief formed: the world is dangerous, I must protect myself at all costs. What happened?',
    'Before safety-seeking, there was exploration. Before the cage, there was the open field. What moment built the cage?',
    'The first time something new resulted in harm. The first time the unknown became the enemy. When?',
    'Safety-seeking is a response to threat. Real threat. When was the threat? What was the threat?',
    'There is a memory where the comfort zone became the only zone. Where leaving felt like death. What memory?',
    'Someone taught you the world is unsafe. By word, by action, by absence. Who was the teacher?',
    'Before the walls, there was openness. Before the armor, there was vulnerability. What moment required armor?',
  ],
};

// ============================================================================
// REFRAME SEEDS (621-740)
// Honoring old protection while opening new perspective
// ============================================================================

export const REFRAME_TEMPLATES = {
  shame: [
    'Shame is not evidence of defect. Shame is evidence of a nervous system that once needed to hide to survive.',
    'What if unworthiness is not truth, but a very old strategy for staying safe in an unsafe place?',
    'The voice that says not-enough is not your voice. It is the voice of someone who could not see you clearly.',
    'Shame kept you small when being big was dangerous. It worked. And now, in safety, it can rest.',
    'What if the flaw is not in you, but in the mirror you were given? What if you were never broken, only badly reflected?',
    'Shame is loyalty to an old verdict. The trial is over. The sentence can be released.',
    'The story of unworthiness protected you from hoping, from trying, from the pain of rejection. It was mercy once. Now it is prison.',
    'What if shame is not the truth of who you are, but the residue of who you had to become to survive who they were?',
  ],
  control: [
    'Control is not pathology. Control is what a brilliant nervous system does when chaos once felt like annihilation.',
    'What if hypervigilance is not anxiety, but a warrior system that never got the memo that the war is over?',
    'The need to manage everything makes sense. Once, nothing was managed for you. You had to become the manager.',
    'Control is the antidote to powerlessness. It worked. You survived. And now, in safety, the grip can soften.',
    'What if letting go is not giving up, but trusting that the future does not require the same armor as the past?',
    'The grip is not weakness. The grip is strength that forgot how to rest.',
    'Control protected you from the terror of unpredictability. It was adaptive. It was necessary. It can also be released.',
    'What if certainty is not safety, but the illusion of safety? And what if you are safe enough to tolerate the truth?',
  ],
  abandonment: [
    'The fear of abandonment is not irrational. It is the body remembering when being left actually meant you were not safe.',
    'What if distance is not rejection, but someone else\'s need for space? What if their leaving says nothing about your worth?',
    'Abandonment is a wound, not a prophecy. The past left. The future is not the past.',
    'Pulling away before they can leave is protection. It worked. You controlled the leaving. And now, you can choose differently.',
    'What if closeness is not inherently dangerous, but dangerous once, in one context, with specific people who could not stay?',
    'The belief that everyone leaves makes sense. Everyone did leave. And those people are not these people.',
    'Abandonment terror is not overreaction. It is accurate reaction to past experience, applied to present circumstance. The body is not wrong. The timeline is.',
    'What if the ones who left were not the final word on your worth? What if their departure was their limit, not your deficiency?',
  ],
  perfectionism: [
    'Perfectionism is not about excellence. It is about survival. Once, being flawless was how you stayed safe, stayed loved, stayed accepted.',
    'What if mistakes are not evidence of failure, but evidence of being human? And what if being human is exactly enough?',
    'The standard is not too high because you are ambitious. The standard is too high because once, anything less resulted in rejection.',
    'Perfectionism protected you from criticism, from judgment, from the unbearable pain of not being enough. It worked. It also exhausted you.',
    'What if good enough is not settling, but sanity? What if done is better than perfect because done lets you live?',
    'The bar keeps rising because the goal is not excellence. The goal is safety. And safety never arrives through performance.',
    'Perfectionism is the costume you wore to earn love. The performance worked. And you can take the costume off now.',
    'What if your worth is not contingent on flawlessness? What if it never was?',
  ],
  victimhood: [
    'Victimhood is not weakness. Victimhood is what happens when power is actually taken and the system needs to make sense of it.',
    'What if powerlessness is not identity, but what you experienced? The event does not have to become the self.',
    'The narrative of no-choice protected you from blame, from responsibility for the unbearable. It was mercy. It also became cage.',
    'Things happened TO you. That is fact. And agency still exists. Both are true. One moves you forward.',
    'What if reclaiming power is not denial of harm, but refusal to let harm be the final word?',
    'Victimhood kept you safe from the terror of responsibility when you had none. You were not responsible then. You are response-able now.',
    'The story of what was done to you is real. The story of what you do next is also real. Both matter. Only one is actionable.',
    'What if you are not defined by what happened, but by how you meet what happened?',
  ],
  'emotional-suppression': [
    'Emotional suppression is not weakness. It is what a brilliant system does when feeling fully would have been overwhelming, dangerous, or not allowed.',
    'What if feelings are not the enemy, but the messengers? And what if you are finally safe enough to receive the message?',
    'Suppression kept you functional when falling apart was not an option. It worked. You survived. And now, you can feel.',
    'What if intensity is not danger, but aliveness? What if the flood you fear is actually the thaw?',
    'The strategy of numbing made sense. No one was there to hold the feeling. You had to hold yourself. By not feeling.',
    'Emotional suppression is not pathology. It is adaptation. And adaptation can update when the environment changes.',
    'What if your feelings are not too much, but were too much for people who could not hold them? Their limit. Not your flaw.',
    'The wall between you and your emotions was not built to punish you. It was built to protect you. It can come down now.',
  ],
  'people-pleasing': [
    'People-pleasing is not weakness. It is what you do when saying no once meant rejection, danger, or loss of love.',
    'What if your needs matter as much as theirs? Not more. Not less. As much.',
    'The strategy of accommodating kept you safe when conflict was dangerous. It worked. You stayed connected. And it also erased you.',
    'People-pleasing is not generosity. It is self-abandonment dressed as kindness. The boundary between them is resentment.',
    'What if disappointing someone does not mean losing them? What if real connection can hold your no?',
    'Saying yes to everyone meant saying no to yourself. The math worked once. It does not work anymore.',
    'The performance of niceness protected you from anger, from rejection, from the terror of being too much. It also prevented being known.',
    'What if you can be kind AND boundaried? What if both are necessary for actual intimacy?',
  ],
  scarcity: [
    'Scarcity is not irrationality. It is what the body believes when not-enough was the reality, not just the fear.',
    'What if there is enough? Not because circumstances guarantee it, but because you are resourceful enough to meet what comes?',
    'The belief in scarcity kept you vigilant, kept you saving, kept you safe when resources were actually scarce. It worked.',
    'Scarcity thinking is not the problem. The problem is when the thinking outlives the circumstance.',
    'What if abundance is not about having more, but about releasing the fear that there will never be enough?',
    'Hoarding made sense when deprivation was real. The strategy protected you. It also prevents you from living openly.',
    'Scarcity is a lens installed by real lack. The lack may have changed. The lens remains. Lenses can be updated.',
    'What if enough is not a destination you arrive at, but a decision you make about what you already have?',
  ],
  comparison: [
    'Comparison is not vanity. It is what happens when worth was measured, ranked, and conditional.',
    'What if your value is not relative, but inherent? Not earned by being better, but given by being here?',
    'Measuring yourself against others made sense when love was competitive, when approval was scarce, when only the best were safe.',
    'Comparison protected you from complacency. It drove you. It also prevented you from resting in your own worth.',
    'What if their success does not diminish you? What if there is enough room for everyone to be whole?',
    'The ranking system was installed early. It promised safety, belonging, love. It delivered exhaustion.',
    'Comparison is not the problem. The belief that your worth depends on the comparison is the problem.',
    'What if you are not in competition with anyone? What if your path is yours alone, and that is enough?',
  ],
  catastrophizing: [
    'Catastrophizing is not irrationality. It is what the nervous system does when disaster arrived without warning and preparation became survival.',
    'What if the worst does not happen as often as your mind rehearses? What if your mind is trying to protect you from a past, not a future?',
    'The spiral made sense when bad things happened and no one prepared you. You became your own early warning system.',
    'Catastrophizing is not pessimism. It is hope in disguise. If I can predict it, maybe I can prevent it.',
    'What if the future is not the past? What if the disaster you are bracing for is not actually coming?',
    'The worst-case thinking protected you from disappointment, from being blindsided, from hope that hurts. It also stole the present.',
    'Catastrophizing is loyalty to a nervous system that learned: bad things come, and I must be ready. You can be ready and also be here.',
    'What if you are more resilient than you think? What if you can handle what comes without rehearsing it in advance?',
  ],
  'identity-fusion': [
    'Identity fusion is not confusion. It is what happens when being someone specific felt safer than being no one.',
    'What if you are not your role? Not your story? Not your trauma? What if you are the one who holds all of these, and is also more?',
    'Fusion made sense when formlessness felt like annihilation. The role gave structure. The label gave belonging. And it also became cage.',
    'The costume of identity protected you from the terror of not knowing who you are. It worked. It also limited you.',
    'What if beneath every label, there is space? And what if the space is not emptiness, but vastness?',
    'Identity fusion is not ego. It is survival. Knowing who you are meant you could be found, understood, accepted.',
    'What if you are allowed to be more than one thing? What if you are allowed to be undefined, unfinished, in process?',
    'The story of who you are is real. And it is also not the whole truth. Both are true. One is liberation.',
  ],
  'safety-seeking': [
    'Safety-seeking is not cowardice. It is what you do when danger was real and the body learned: careful is how you survive.',
    'What if the walls you built to protect yourself are now the walls that keep you from living?',
    'Staying safe made sense when the world was unsafe. The strategy worked. You are here. And being here now asks for something different.',
    'Safety-seeking is not wrong. It is incomplete. Safety without risk is survival. Survival without risk is not the same as living.',
    'What if growth requires the very thing you have been avoiding? And what if you are ready for it?',
    'The comfort zone protected you from harm. It also protected you from possibility. Both are true. One is smaller than you are.',
    'Safety is not the problem. The belief that safety is more important than aliveness is the problem.',
    'What if you are brave enough to be uncertain? What if you are strong enough to not know? What if safety is overrated?',
  ],
};