import type { Insight } from '../types/toolkit';

export const SAMPLE_INSIGHTS: Insight[] = [
  {
    id: 'ins_001_shame',
    title: "Shame Isn't the Truth",
    body: 'Shame tells you "I am bad." But shame is a feeling, not a fact. It\'s your brain trying to protect you from social rejection by making you believe you\'re fundamentally flawed. The truth: you made mistakes. You\'re not a mistake. Your worth isn\'t determined by your worst moments. Shame loses power when you speak it out loud to someone safe.',
    pillar_id: 'SR',
    core_truth: 'Shame is a signal, not your identity',
    schema_targets: ['shame_spiral', 'self_compassion', 'worthiness'],
    mindblock_targets: ['personalization', 'labeling'],
    variants: {
      card: 'Shame says "I am bad." But that\'s a feeling, not a fact. Your worth isn\'t defined by your worst moments.',
      full: 'Shame tells you "I am bad." But shame is a feeling, not a fact. It\'s your brain trying to protect you from social rejection by making you believe you\'re fundamentally flawed. The truth: you made mistakes. You\'re not a mistake. Your worth isn\'t determined by your worst moments. Shame loses power when you speak it out loud to someone safe. It thrives in secrecy and dies in connection. Next time shame shows up, try this: Name it. "I\'m feeling shame right now." Then reality-test it. "Is this shame telling me I\'m bad, or guilt telling me I did something I regret?" Shame wants you alone. Recovery happens in connection.',
      voice_script: 'Listen. Shame is going to tell you that you are fundamentally bad. Broken. Unworthy. But here\'s what shame actually is: a feeling. Not a fact. You made mistakes, yes. But you are not a mistake. Shame loses its grip when you speak it out loud to someone who won\'t confirm the story. Try this right now: "I\'m feeling shame." Say it out loud. Notice how naming it creates just a little distance. You\'re not shame. You\'re experiencing shame. And that changes everything.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_003_sr_shame'],
    related_practices: ['prac_007_self_compassion', 'prac_009_voicing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_002_isolation',
    title: 'Isolation Is the Symptom',
    body: 'When you isolate, you think it\'s because you\'re protecting others from your mess. But isolation is the symptom, not the solution. Your nervous system treats loneliness like physical pain. And pain seeks relief. Connection doesn\'t just feel good, it regulates your biology. You can\'t heal alone.',
    pillar_id: 'CR',
    core_truth: 'You can\'t regulate alone',
    schema_targets: ['connection', 'belonging', 'nervous_system_regulation'],
    mindblock_targets: ['mind_reading', 'catastrophizing'],
    variants: {
      card: 'You think isolation protects others from your mess. But loneliness is pain. And pain seeks relief. You can\'t heal alone.',
      full: 'When you isolate, you think it\'s because you\'re protecting others from your mess. Or maybe you believe if they really knew you, they\'d leave. So you hide. But here\'s the thing: isolation is the symptom, not the solution. Your nervous system treats loneliness like physical pain. And what does pain do? It seeks relief. Connection doesn\'t just feel good, it regulates your biology. When you\'re with someone safe, your stress hormones drop. Your heart rate variability improves. Your nervous system borrows regulation from theirs. You literally cannot heal in isolation. Recovery happens in relationship. Start with one person. One safe relationship where you can be seen.',
      voice_script: 'I know you\'re isolating right now. And I know it feels like protection. If you stay hidden, no one can reject you, right? But isolation is the problem, not the solution. Your brain treats loneliness like a wound. And wounds need tending. Connection regulates your nervous system. You can\'t do this alone. And you don\'t have to. What would it look like to reach out to one person today? Just one. Not to fix anything. Just to be seen.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_007_cr_connection'],
    related_practices: ['prac_006_reach_out', 'prac_009_voicing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_003_regulation',
    title: 'Regulation Isn\'t Control',
    body: 'You don\'t need to control your emotions. You need to expand your capacity to be WITH them. Regulation isn\'t suppression. It\'s widening your window of tolerance so feelings can move through you without hijacking you. The goal isn\'t calm all the time. It\'s resilience.',
    pillar_id: 'ER',
    core_truth: 'Feel it without becoming it',
    schema_targets: ['window_of_tolerance', 'nervous_system_regulation', 'emotional_capacity'],
    mindblock_targets: ['all_or_nothing', 'should_statements'],
    variants: {
      card: 'Regulation isn\'t control. It\'s expanding your capacity to be WITH emotions without being hijacked by them.',
      full: 'You don\'t need to control your emotions. You need to expand your capacity to be WITH them. Here\'s the difference: Control says, "Don\'t feel that. Push it down. Be calm." Regulation says, "I\'m feeling this. It\'s intense. But it won\'t last forever. I can be with it." Regulation isn\'t suppression. It\'s widening your window of tolerance so feelings can move through you without overwhelming you or shutting you down. The goal isn\'t to be calm all the time. The goal is resilience: the ability to feel something hard and not need to escape it immediately. That\'s where recovery happens.',
      voice_script: 'Let me tell you something about emotions. You don\'t need to control them. You need to build capacity to be with them. Regulation isn\'t about staying calm. It\'s about staying present. When a big feeling shows up, you don\'t have to push it away or drown in it. You can notice it. Name it. Feel it without becoming it. That\'s the practice. Not control. Capacity.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_001_er_window'],
    related_practices: ['prac_001_box_breathing', 'prac_002_grounding'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_004_secrecy',
    title: 'Secrets Drain You',
    body: 'Every secret you keep requires cognitive energy. Your brain has to monitor who knows what, edit your story in real-time, and suppress the truth constantly. This isn\'t just exhausting. It floods your system with stress hormones. What you hide owns you. What you speak loses power.',
    pillar_id: 'SR',
    core_truth: 'What you hide owns you',
    schema_targets: ['secrecy', 'shame_spiral', 'authenticity'],
    mindblock_targets: ['catastrophizing', 'mind_reading'],
    variants: {
      card: 'Secrets drain your brain and flood you with stress hormones. What you hide owns you. What you speak loses power.',
      full: 'Every secret you keep requires cognitive energy. Your brain has to monitor who knows what, edit your story in real-time, and suppress the truth constantly. This isn\'t just exhausting. It floods your system with stress hormones. Studies show that keeping secrets reduces working memory, increases rumination, and weakens immune function. What you hide owns you. It loops in your mind, grows heavier, feeds shame. But what you speak out loud? It loses power. Not because the truth disappears, but because you\'re no longer carrying it alone. Find one safe person. Share one secret. Notice what shifts.',
      voice_script: 'You\'re carrying something heavy. A secret that feels too big to speak. But here\'s what secrets do: they drain you. Your brain is working overtime to keep track of who knows what, editing every conversation, suppressing the truth. That\'s exhausting. And it\'s making you sick. What you hide owns you. But what you speak? It loses its grip. Not all at once. But enough to breathe. Who\'s one safe person you could tell?',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_004_sr_secrecy'],
    related_practices: ['prac_009_voicing', 'prac_010_writing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_005_triggers',
    title: 'Triggers Are Protectors',
    body: 'A trigger isn\'t weakness. It\'s your nervous system trying to keep you safe from what hurt you before. It reacts in milliseconds, before your rational brain even knows what\'s happening. You\'re not broken. Your system is doing exactly what it was trained to do. Recovery is teaching it new responses.',
    pillar_id: 'ER',
    core_truth: 'Triggers protect, they don\'t define you',
    schema_targets: ['trigger_awareness', 'nervous_system_regulation', 'self_compassion'],
    mindblock_targets: ['should_statements', 'labeling'],
    variants: {
      card: 'Triggers aren\'t weakness. They\'re your nervous system trying to protect you from past pain. You\'re not broken.',
      full: 'A trigger isn\'t weakness. It\'s your nervous system trying to keep you safe from what hurt you before. When you encounter something that resembles a past threat, your amygdala reacts in milliseconds before your rational brain even knows what\'s happening. Fight, flight, freeze, or use. You\'re not choosing to react. Your system is doing exactly what it was trained to do based on your history. You\'re not broken. Your nervous system is working. It\'s just working off old information. Recovery is about teaching it new responses: This resembles the past, but it\'s not the same. I\'m safe enough now to pause. I have choices. That takes time. Be patient with your triggers. They\'re trying to help.',
      voice_script: 'When you get triggered, it feels like you\'re weak. Like you should be over this by now. But here\'s the truth: triggers are your nervous system trying to protect you. It detects something that resembles past pain and reacts instantly. You\'re not choosing this. Your system is running an old program. And that\'s okay. Recovery isn\'t about eliminating triggers. It\'s about building new responses. Slowly. With compassion. You\'re not broken. You\'re learning.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_002_er_triggers'],
    related_practices: ['prac_002_grounding', 'prac_003_pause'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_006_identity',
    title: 'You\'re Not Just in Recovery',
    body: 'Recovery is part of your story, not the whole story. When your entire identity revolves around what you\'re NOT doing, you\'re still defined by addiction. You\'re allowed to be multiple things: someone healing AND someone with interests, dreams, creativity. Identity is bigger than your diagnosis.',
    pillar_id: 'SC',
    core_truth: 'You contain multitudes',
    schema_targets: ['identity', 'growth_mindset', 'authenticity'],
    mindblock_targets: ['labeling', 'all_or_nothing'],
    variants: {
      card: 'You\'re not just "in recovery." You\'re also creative, curious, complex. Your identity is bigger than your diagnosis.',
      full: 'Recovery is part of your story, not the whole story. When your entire identity revolves around what you\'re NOT doing (not using, not relapsing, not failing), you\'re still defined by addiction. It\'s just a different cage. You\'re allowed to be multiple things. Someone in recovery AND someone with interests, passions, creativity, humor, depth. Someone learning, growing, evolving. "I\'m an addict" can be a powerful truth in early recovery. But it doesn\'t have to be the ONLY truth forever. You contain multitudes. Let yourself discover who you\'re becoming beyond the identity of struggle.',
      voice_script: 'I see you working so hard at recovery. And that matters. But I also see something else: you\'re more than your recovery. You\'re not just someone in recovery. You\'re also someone with interests, curiosity, creativity. Someone becoming. Recovery is part of your story, yes. But it\'s not the whole story. Who else are you? What else lights you up? You\'re allowed to explore that.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_005_sc_identity'],
    related_practices: ['prac_004_values', 'prac_010_writing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_007_boundaries',
    title: 'No Is a Full Sentence',
    body: 'You don\'t owe anyone an explanation for protecting yourself. "No" is a complete sentence. Boundaries aren\'t mean. They\'re how you stay in integrity with your values and protect your capacity to show up. If someone can\'t handle your boundaries, they can\'t handle you.',
    pillar_id: 'CR',
    core_truth: 'Boundaries protect your recovery',
    schema_targets: ['boundaries', 'self_advocacy', 'worthiness'],
    mindblock_targets: ['should_statements', 'people_pleasing'],
    variants: {
      card: '"No" is a full sentence. Boundaries aren\'t mean. They protect your capacity to show up authentically.',
      full: 'You don\'t owe anyone an explanation for protecting yourself. "No" is a complete sentence. Not "I can\'t because..." or "I\'m sorry but..." Just "No. That doesn\'t work for me." Boundaries aren\'t mean. They\'re not rejection. They\'re how you stay in integrity with your values and protect your capacity to show up. Without boundaries, you say yes when you mean no, you absorb everyone\'s emotions, you fix everyone\'s problems, and you end up resentful and exhausted. Resentment is a relapse risk. Boundaries prevent resentment. If someone can\'t handle your boundaries, they can\'t handle the real you. And that\'s information.',
      voice_script: 'You feel guilty setting boundaries. Like saying no makes you selfish. But here\'s the thing: "No" is a full sentence. You don\'t need to justify protecting yourself. Boundaries aren\'t rejection. They\'re how you preserve your energy, your values, your recovery. If someone can\'t handle your boundary, that\'s their work, not yours. You\'re allowed to protect yourself. Without explanation. Without guilt.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_008_cr_boundaries'],
    related_practices: ['prac_005_boundary', 'prac_009_voicing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_008_reactions',
    title: 'React vs. Respond',
    body: 'A reaction is automatic: threat detected, nervous system hijacked, old pattern activated. A response is chosen: pause created, options considered, value-aligned action taken. You can\'t always control the initial reaction. But you can build the pause that creates response.',
    pillar_id: 'DM',
    core_truth: 'Pause creates choice',
    schema_targets: ['choice_access', 'window_of_tolerance', 'impulse_control'],
    mindblock_targets: ['emotional_reasoning', 'all_or_nothing'],
    variants: {
      card: 'Reaction is automatic. Response is chosen. The pause between them is where recovery lives.',
      full: 'A reaction is automatic: threat detected, amygdala fires, nervous system hijacked, old pattern activated. It happens in milliseconds. A response is chosen: pause created, prefrontal cortex engaged, options considered, value-aligned action taken. You can\'t always control the initial reaction. Your nervous system moves faster than your thoughts. But you CAN build the pause that creates space for response. Even 3 seconds changes your brain state. Breathing. Counting. Stepping outside. The pause is where recovery lives. Between stimulus and response is your freedom.',
      voice_script: 'When something activates you, your nervous system reacts instantly. Fight, flight, freeze, use. That\'s automatic. But here\'s what you can build: a pause. Just a few seconds between the trigger and your action. That pause is where choice lives. Reaction is automatic. Response is chosen. And recovery is the practice of building that pause, over and over, until responding becomes your new default.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_010_dm_decisions'],
    related_practices: ['prac_003_pause', 'prac_001_box_breathing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_009_purpose',
    title: 'Purpose Isn\'t a Destination',
    body: 'You don\'t find purpose. You live into it through curiosity, experimentation, and showing up. Meaning emerges from what captures your attention, what moves you, what you can\'t stop thinking about. Not from a grand plan. Trust the process.',
    pillar_id: 'II',
    core_truth: 'Meaning emerges, it\'s not manufactured',
    schema_targets: ['meaning_making', 'authenticity', 'growth_mindset'],
    mindblock_targets: ['should_statements', 'all_or_nothing'],
    variants: {
      card: 'Purpose isn\'t found, it\'s lived into. Through curiosity. Through experiments. Through what moves you.',
      full: 'You don\'t find purpose like a treasure buried in the sand. Purpose emerges through living. Through curiosity, experimentation, paying attention to what lights you up. Meaning comes from what captures your attention, what moves you to tears, what you think about when no one\'s watching. Not from a grand plan or a "should." You\'re allowed to try things, change your mind, explore. Purpose isn\'t a destination you arrive at. It\'s a direction you walk in. Trust that showing up with curiosity will reveal the path.',
      voice_script: 'I know you\'re searching for purpose. For the reason you went through all this pain. But purpose isn\'t something you find. It\'s something you live into. Pay attention to what captures your attention. What moves you. What you\'d do even if no one was watching. That\'s where meaning lives. Not in a grand plan. In small moments of aliveness. Trust that.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_009_ii_meaning'],
    related_practices: ['prac_004_values', 'prac_010_writing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_010_nervous',
    title: 'Safety Is Felt, Not Thought',
    body: 'Your nervous system doesn\'t respond to logic. You can\'t think your way to feeling safe. Safety is a body experience: slower breath, softer muscles, heart rate settling. Build safety through co-regulation, rhythm, and practices that signal to your body: we\'re okay right now.',
    pillar_id: 'ER',
    core_truth: 'Safety is sensed in the body',
    schema_targets: ['nervous_system_regulation', 'embodiment', 'safety'],
    mindblock_targets: ['should_statements'],
    variants: {
      card: 'You can\'t think your way to feeling safe. Safety is sensed in the body through breath, rhythm, connection.',
      full: 'Your nervous system doesn\'t respond to logic. You can tell yourself "I\'m safe" all day, but if your body is still in threat mode, you won\'t feel it. Safety is a body experience: slower breath, softer muscles, heart rate variability improving. You build safety through practices that signal to your nervous system "we\'re okay right now." Breathing. Movement. Co-regulation with safe people. Rhythm. Predictability. This is why connection matters. Why breathing works. Why grounding helps. You\'re not talking to your thoughts. You\'re speaking to your body.',
      voice_script: 'You can\'t think your way to feeling safe. Your nervous system doesn\'t care about logic. It cares about signals. Is your breath steady? Are your muscles tense or soft? Is someone safe nearby? Safety is felt in the body, not reasoned in the mind. So when you\'re activated, don\'t try to convince yourself you\'re safe. Show your body. Breathe. Move. Ground. That\'s how safety returns.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_001_er_window'],
    related_practices: ['prac_001_box_breathing', 'prac_002_grounding'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_011_no',
    title: 'People-Pleasing Is Self-Abandonment',
    body: 'Every time you say yes when you mean no, you\'re choosing them over you. People-pleasing isn\'t kindness. It\'s fear of rejection disguised as generosity. Real relationships can handle your truth. Practice saying no to others so you can say yes to yourself.',
    pillar_id: 'CR',
    core_truth: 'Your needs matter too',
    schema_targets: ['boundaries', 'self_advocacy', 'authenticity'],
    mindblock_targets: ['people_pleasing', 'should_statements'],
    variants: {
      card: 'People-pleasing isn\'t kindness. It\'s fear of rejection. Real relationships can handle your truth.',
      full: 'Every time you say yes when you mean no, you\'re choosing them over you. You\'re abandoning yourself to preserve connection. But here\'s the thing: people-pleasing isn\'t kindness. It\'s fear of rejection disguised as generosity. You\'re so afraid they\'ll leave if you have needs that you hide yourself completely. But relationships built on performance aren\'t real. They\'re transactions. Real relationships can handle your truth. Your no. Your limits. Your needs. Practice saying no to others so you can say yes to yourself. That\'s not selfish. That\'s integrity.',
      voice_script: 'You say yes when you mean no. You override your limits to keep the peace. But that\'s not kindness. That\'s self-abandonment. People-pleasing is fear: if they see my needs, they\'ll leave. But real relationships can handle your truth. Your boundaries. Your no. Start practicing: "I can\'t do that." Notice the guilt. Do it anyway. You matter too.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_008_cr_boundaries'],
    related_practices: ['prac_005_boundary', 'prac_009_voicing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_012_worth',
    title: 'You Don\'t Earn Worth',
    body: 'Worth isn\'t something you achieve. It\'s inherent. You don\'t have to be sober enough, healed enough, successful enough, or perfect enough to matter. You matter because you exist. Full stop. Recovery isn\'t about becoming worthy. It\'s about recognizing you always were.',
    pillar_id: 'SC',
    core_truth: 'You already matter',
    schema_targets: ['worthiness', 'self_compassion', 'belonging'],
    mindblock_targets: ['should_statements', 'personalization'],
    variants: {
      card: 'You don\'t earn worth. It\'s not conditional on sobriety, success, or perfection. You matter because you exist.',
      full: 'Worth isn\'t something you achieve or earn. It\'s not conditional on being sober enough, healed enough, successful enough, or perfect enough. You matter because you exist. Full stop. If you learned that love is conditional, this sounds absurd. Dangerous, even. But the performance trap is exhausting. You can\'t maintain perfection forever. Recovery isn\'t about finally becoming worthy. It\'s about recognizing you always were. This isn\'t about affirmations. It\'s about corrective experiences: being seen in your mess and not abandoned. Failing and still belonging. You don\'t need to become good enough. You already are.',
      voice_script: 'You think worth is something you earn through being sober, successful, perfect. But that\'s a lie you learned. Worth isn\'t conditional. You matter because you exist. Not because you achieved something. Not because you\'re healed. Because you\'re here. Recovery isn\'t about becoming worthy. It\'s about recognizing you already are.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_006_sc_worth'],
    related_practices: ['prac_007_self_compassion', 'prac_008_mirror'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_013_belonging',
    title: 'Belonging Isn\'t Performance',
    body: 'You don\'t have to perform to belong. Real belonging happens when you show up as you are, messy and imperfect, and you\'re still welcomed. Hiding yourself to fit in isn\'t belonging. It\'s conformity. And it\'s exhausting.',
    pillar_id: 'CR',
    core_truth: 'You belong as you are',
    schema_targets: ['belonging', 'authenticity', 'connection'],
    mindblock_targets: ['people_pleasing', 'mind_reading'],
    variants: {
      card: 'You don\'t perform your way to belonging. Real belonging happens when you\'re messy and still welcomed.',
      full: 'You don\'t have to perform to belong. Hiding your struggles, editing your story, pretending to be fine when you\'re not—that\'s not belonging. That\'s conformity. Real belonging happens when you show up as you are, messy and imperfect and struggling, and you\'re still welcomed. Still seen. Still valued. It\'s terrifying to test. What if I\'m real and they leave? But if someone only accepts the polished version of you, they don\'t actually know you. And that\'s lonely even when you\'re surrounded. Find the people who can handle your truth. That\'s where belonging lives.',
      voice_script: 'You think you have to perform to belong. Be helpful, be fine, be easy. But that\'s not belonging. That\'s exhausting. Real belonging happens when you show up messy and you\'re still welcomed. When you tell the truth and people stay. That\'s where connection lives. Not in performance. In presence.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_007_cr_connection'],
    related_practices: ['prac_006_reach_out', 'prac_009_voicing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_014_becoming',
    title: 'You\'re Not Fixed',
    body: 'Recovery isn\'t about returning to who you were before addiction. It\'s about becoming who you couldn\'t be while using. You\'re not fixed. You\'re unfolding. Every choice is shaping the person you\'re becoming. That\'s power.',
    pillar_id: 'SC',
    core_truth: 'You\'re becoming',
    schema_targets: ['identity', 'growth_mindset', 'agency'],
    mindblock_targets: ['labeling', 'all_or_nothing'],
    variants: {
      card: 'Recovery isn\'t returning to who you were. It\'s becoming who you couldn\'t be while using. You\'re unfolding.',
      full: 'Recovery isn\'t about returning to who you were before addiction. That person doesn\'t exist anymore. And that\'s okay. Recovery is about becoming who you couldn\'t be while using. Someone present. Someone choosing. Someone learning. You\'re not fixed. You\'re not a static self trapped in recovery. You\'re unfolding. Every choice you make is shaping the person you\'re becoming. Every time you stay present instead of numbing, you\'re building a new neural pathway. Every time you reach out instead of isolating, you\'re training a new default. That\'s not just sobriety. That\'s transformation. And you\'re the one creating it.',
      voice_script: 'You\'re not going back to who you were before addiction. That person is gone. And recovery isn\'t about fixing yourself into some ideal. It\'s about becoming. Unfolding. Every choice you make is shaping who you\'re becoming. You\'re not fixed. You\'re evolving. And that\'s powerful.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_005_sc_identity'],
    related_practices: ['prac_004_values', 'prac_010_writing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_015_truth',
    title: 'Truth Is Medicine',
    body: 'Every time you tell the truth about what you\'re feeling, you\'re training your nervous system that it\'s safe to be real. Truth is medicine. Not because it\'s easy, but because it\'s the opposite of the hiding that kept you sick. Speak it. Even when your voice shakes.',
    pillar_id: 'SR',
    core_truth: 'Truth heals hiding',
    schema_targets: ['authenticity', 'shame_spiral', 'connection'],
    mindblock_targets: ['catastrophizing'],
    variants: {
      card: 'Truth is medicine. Every time you speak what\'s real, you train your nervous system it\'s safe to be seen.',
      full: 'Every time you tell the truth about what you\'re feeling, what you\'re struggling with, what you need, you\'re training your nervous system that it\'s safe to be real. Truth is medicine. Not because it makes everything better instantly. But because it\'s the opposite of the hiding that kept you sick. Secrets fed your shame. Performance drained your energy. Pretending kept you isolated. Truth creates connection. It reality-tests your fears. It builds trust. Speak it. Even when your voice shakes. Even when you\'re scared. That\'s where healing happens.',
      voice_script: 'Truth is medicine. Every time you speak what\'s real, you\'re healing. Not because truth fixes everything. But because hiding made you sick. Secrets fed shame. Pretending drained you. Truth creates connection. So speak it. Even when you\'re terrified. Even when your voice shakes. That\'s courage.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_004_sr_secrecy'],
    related_practices: ['prac_009_voicing', 'prac_010_writing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_016_enough',
    title: 'You Are Enough Right Now',
    body: 'Not when you\'re healed. Not when you hit a milestone. Not when you\'ve proven yourself. Right now. Exactly as you are. With all the mess and the struggle and the doubt. You are enough. This is the hardest truth to believe. And the most important.',
    pillar_id: 'SC',
    core_truth: 'You\'re enough now',
    schema_targets: ['worthiness', 'self_compassion'],
    mindblock_targets: ['should_statements', 'all_or_nothing'],
    variants: {
      card: 'You\'re enough right now. Not later. Not when you\'re healed. Right now. Exactly as you are.',
      full: 'You are enough right now. Not when you\'re healed. Not when you hit 30 days, 90 days, a year. Not when you\'ve proven yourself worthy through perfect recovery. Right now. Exactly as you are. With all the mess and the struggle and the doubt and the fear. You are enough. This is the hardest truth to believe. Especially if you learned that love is conditional. That worth is earned. That you have to be better before you matter. But that\'s the lie that fed your addiction. Recovery is unlearning it. You are enough. Right now.',
      voice_script: 'Listen to me. You are enough. Right now. Not later when you\'re fixed or healed or perfect. Right now. With all your struggles and doubts and mess. You are enough. I know that\'s hard to believe. But it\'s the truth. You don\'t have to earn your worth. You already have it.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_006_sc_worth'],
    related_practices: ['prac_007_self_compassion', 'prac_008_mirror'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_017_becoming',
    title: 'Small Choices Build Selves',
    body: 'You don\'t become a different person overnight. You become through small, repeated choices. Every time you choose differently, you\'re wiring a new neural pathway. Every time you stay present, you\'re building a new default. Identity is practice.',
    pillar_id: 'II',
    core_truth: 'You build who you become',
    schema_targets: ['identity', 'agency', 'growth_mindset'],
    mindblock_targets: ['all_or_nothing'],
    variants: {
      card: 'You don\'t transform overnight. You become through small, repeated choices. Identity is practice.',
      full: 'You don\'t become a different person overnight. You become through small, repeated choices. Every time you pause instead of react, you\'re wiring a new neural pathway. Every time you reach out instead of isolate, you\'re building a new default. Every time you choose aligned with your values instead of your impulses, you\'re practicing a new identity. This is how transformation works. Not dramatic revelation. Incremental repetition. Identity isn\'t who you say you are. It\'s what you do when no one\'s watching. You\'re building who you\'re becoming. One choice at a time.',
      voice_script: 'You don\'t transform in one moment. You become through small choices, repeated over time. Every time you pause, every time you reach out, every time you choose differently, you\'re building new wiring. Identity is practice. And you\'re practicing a new self. One choice at a time.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_009_ii_meaning'],
    related_practices: ['prac_004_values', 'prac_010_writing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_018_crisis',
    title: 'Crisis Plans Work',
    body: 'You can\'t make decisions in crisis. Your prefrontal cortex is offline. So make the decisions NOW. When you\'re calm. Write your crisis plan. Who to call. What to do first. Where to go. Execute it when the moment comes. Don\'t improvise recovery.',
    pillar_id: 'DM',
    core_truth: 'Decide before crisis hits',
    schema_targets: ['crisis_planning', 'choice_access', 'agency'],
    mindblock_targets: ['emotional_reasoning'],
    variants: {
      card: 'You can\'t decide in crisis. Your brain is offline. Make your plan NOW when you\'re calm. Then execute it.',
      full: 'You can\'t make decisions in crisis. When you\'re dysregulated, your prefrontal cortex (the decision-making part of your brain) goes offline. You don\'t have access to rational thought or future consequences. You\'re in survival mode. So make the decisions NOW. When you\'re calm. When you can think. Write your crisis plan. Who will you call? What regulation tool will you try first? Where will you go (or what space will you leave)? What reminder do you need of why you\'re choosing differently? Then when crisis hits, don\'t improvise. Execute the plan. You already decided. Now follow through.',
      voice_script: 'In crisis, you can\'t think clearly. Your decision-making brain is offline. So don\'t wait until crisis to make a plan. Decide now. Who will you call? What will you do first? Where will you go? Write it down. Then when the moment comes, you\'re not deciding. You\'re executing. That\'s how recovery survives crisis.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_010_dm_decisions'],
    related_practices: ['prac_003_pause', 'prac_001_box_breathing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_019_pause',
    title: 'The Pause Is Power',
    body: 'Between stimulus and response is a space. In that space is your power to choose. The pause doesn\'t have to be long. Even 3 seconds changes your brain state. Breathe. Count. Step outside. That pause is where freedom lives.',
    pillar_id: 'DM',
    core_truth: 'Pause creates choice',
    schema_targets: ['choice_access', 'impulse_control', 'agency'],
    mindblock_targets: ['emotional_reasoning', 'all_or_nothing'],
    variants: {
      card: 'Between stimulus and response is a space. In that space is your power. The pause is freedom.',
      full: 'Between stimulus and response is a space. In that space is your power to choose. Viktor Frankl said it. Neuroscience confirms it. The pause doesn\'t have to be long. Even 3 seconds changes your brain state. Your heart rate shifts. Your prefrontal cortex comes back online. Options become visible. The pause is how you move from reaction (automatic, old pattern) to response (chosen, value-aligned). Breathe. Count to 5. Step outside. Splash water on your face. That pause is where freedom lives. Practice it when you don\'t need it, so it\'s there when you do.',
      voice_script: 'Between what happens and how you respond is a pause. That pause is your power. It doesn\'t have to be long. Just 3 seconds. Breathe. Count. Create space. That\'s where choice lives. That\'s where freedom is. The pause is everything.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_010_dm_decisions'],
    related_practices: ['prac_003_pause', 'prac_001_box_breathing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'ins_020_choice',
    title: 'You Always Have a Choice',
    body: 'Even when it doesn\'t feel like it. Even when the pull is overwhelming. Even when every part of you is screaming for relief. You have a choice. It might be the hardest choice you\'ve ever made. But it\'s there. And making it changes your brain.',
    pillar_id: 'DM',
    core_truth: 'Choice exists even in crisis',
    schema_targets: ['agency', 'choice_access', 'empowerment'],
    mindblock_targets: ['helplessness', 'all_or_nothing'],
    variants: {
      card: 'You always have a choice. Even when it doesn\'t feel like it. Even in crisis. The choice is there.',
      full: 'You always have a choice. Even when it doesn\'t feel like it. Even when the pull toward using is overwhelming. Even when every part of you is screaming for relief. The choice is there. It might be the hardest choice you\'ve ever made. It might not feel fair that you have to make it. But it exists. And making it, even once, changes your brain. You\'re building evidence: I can choose differently. I can survive discomfort. I have agency. That\'s not just willpower. That\'s neuroplasticity. You\'re rewiring. One choice at a time.',
      voice_script: 'You always have a choice. I know it doesn\'t feel like it right now. I know the pull is overwhelming. But the choice is there. It\'s hard. It might be the hardest thing you\'ve ever done. But you can make it. And making it changes your brain. You\'re proving to yourself: I have agency. I can choose. That\'s power.',
    },
    response_contract: {
      type: 'slider',
      prompt: 'Does this resonate with you?',
    },
    related_articles: ['art_010_dm_decisions'],
    related_practices: ['prac_003_pause', 'prac_001_box_breathing'],
    created_at: '2024-12-30T00:00:00Z',
    status: 'published',
  },
];